DELETE FROM vocabularies;

-- ============================================================
-- ENGLISH A1 (Beginner) — 50 words, difficulty 1
-- ============================================================
INSERT INTO vocabularies (word, meaning, language, level, difficulty, category, ipa, pinyin) VALUES
('Hello', 'Xin chào', 'en', 'A1', 1, 'greeting', '/həˈloʊ/', NULL),
('Goodbye', 'Tạm biệt', 'en', 'A1', 1, 'greeting', '/ɡʊdˈbaɪ/', NULL),
('Thank you', 'Cảm ơn', 'en', 'A1', 1, 'greeting', '/θæŋk juː/', NULL),
('Please', 'Làm ơn', 'en', 'A1', 1, 'greeting', '/pliːz/', NULL),
('Water', 'Nước', 'en', 'A1', 1, 'food', '/ˈwɔːtər/', NULL),
('Food', 'Thức ăn', 'en', 'A1', 1, 'food', '/fuːd/', NULL),
('House', 'Ngôi nhà', 'en', 'A1', 1, 'place', '/haʊs/', NULL),
('School', 'Trường học', 'en', 'A1', 1, 'place', '/skuːl/', NULL),
('Family', 'Gia đình', 'en', 'A1', 1, 'people', '/ˈfæməli/', NULL),
('Friend', 'Bạn bè', 'en', 'A1', 1, 'people', '/frɛnd/', NULL),
('Book', 'Quyển sách', 'en', 'A1', 1, 'object', '/bʊk/', NULL),
('Teacher', 'Giáo viên', 'en', 'A1', 1, 'people', '/ˈtiːtʃər/', NULL),
('Student', 'Học sinh', 'en', 'A1', 1, 'people', '/ˈstjuːdənt/', NULL),
('Morning', 'Buổi sáng', 'en', 'A1', 1, 'time', '/ˈmɔːrnɪŋ/', NULL),
('Night', 'Buổi tối', 'en', 'A1', 1, 'time', '/naɪt/', NULL),
('Happy', 'Vui vẻ', 'en', 'A1', 1, 'emotion', '/ˈhæpi/', NULL),
('Beautiful', 'Đẹp', 'en', 'A1', 1, 'adjective', '/ˈbjuːtɪfəl/', NULL),
('Big', 'To, lớn', 'en', 'A1', 1, 'adjective', '/bɪɡ/', NULL),
('Small', 'Nhỏ', 'en', 'A1', 1, 'adjective', '/smɔːl/', NULL),
('Money', 'Tiền', 'en', 'A1', 1, 'object', '/ˈmʌni/', NULL),
('Cat', 'Con mèo', 'en', 'A1', 1, 'animal', '/kæt/', NULL),
('Dog', 'Con chó', 'en', 'A1', 1, 'animal', '/dɒɡ/', NULL),
('Fish', 'Con cá', 'en', 'A1', 1, 'animal', '/fɪʃ/', NULL),
('Bird', 'Con chim', 'en', 'A1', 1, 'animal', '/bɜːrd/', NULL),
('Red', 'Màu đỏ', 'en', 'A1', 1, 'color', '/rɛd/', NULL),
('Blue', 'Màu xanh dương', 'en', 'A1', 1, 'color', '/bluː/', NULL),
('Green', 'Màu xanh lá', 'en', 'A1', 1, 'color', '/ɡriːn/', NULL),
('Yellow', 'Màu vàng', 'en', 'A1', 1, 'color', '/ˈjɛloʊ/', NULL),
('White', 'Màu trắng', 'en', 'A1', 1, 'color', '/waɪt/', NULL),
('Black', 'Màu đen', 'en', 'A1', 1, 'color', '/blæk/', NULL),
('Mother', 'Mẹ', 'en', 'A1', 1, 'people', '/ˈmʌðər/', NULL),
('Father', 'Bố', 'en', 'A1', 1, 'people', '/ˈfɑːðər/', NULL),
('Brother', 'Anh/em trai', 'en', 'A1', 1, 'people', '/ˈbrʌðər/', NULL),
('Sister', 'Chị/em gái', 'en', 'A1', 1, 'people', '/ˈsɪstər/', NULL),
('Doctor', 'Bác sĩ', 'en', 'A1', 1, 'people', '/ˈdɒktər/', NULL),
('Car', 'Xe hơi', 'en', 'A1', 1, 'object', '/kɑːr/', NULL),
('Phone', 'Điện thoại', 'en', 'A1', 1, 'object', '/foʊn/', NULL),
('Table', 'Cái bàn', 'en', 'A1', 1, 'object', '/ˈteɪbəl/', NULL),
('Chair', 'Cái ghế', 'en', 'A1', 1, 'object', '/tʃɛər/', NULL),
('Door', 'Cánh cửa', 'en', 'A1', 1, 'object', '/dɔːr/', NULL),
('Window', 'Cửa sổ', 'en', 'A1', 1, 'object', '/ˈwɪndoʊ/', NULL),
('Eat', 'Ăn', 'en', 'A1', 1, 'action', '/iːt/', NULL),
('Drink', 'Uống', 'en', 'A1', 1, 'action', '/drɪŋk/', NULL),
('Run', 'Chạy', 'en', 'A1', 1, 'action', '/rʌn/', NULL),
('Walk', 'Đi bộ', 'en', 'A1', 1, 'action', '/wɔːk/', NULL),
('Sleep', 'Ngủ', 'en', 'A1', 1, 'action', '/sliːp/', NULL),
('Rain', 'Mưa', 'en', 'A1', 1, 'weather', '/reɪn/', NULL),
('Sun', 'Mặt trời', 'en', 'A1', 1, 'weather', '/sʌn/', NULL),
('Cold', 'Lạnh', 'en', 'A1', 1, 'adjective', '/koʊld/', NULL),
('Hot', 'Nóng', 'en', 'A1', 1, 'adjective', '/hɒt/', NULL);

-- ============================================================
-- ENGLISH A2 (Elementary) — 40 words, difficulty 1
-- ============================================================
INSERT INTO vocabularies (word, meaning, language, level, difficulty, category, ipa, pinyin) VALUES
('Appointment', 'Cuộc hẹn', 'en', 'A2', 1, 'daily', '/əˈpɔɪntmənt/', NULL),
('Experience', 'Kinh nghiệm', 'en', 'A2', 1, 'abstract', '/ɪkˈspɪəriəns/', NULL),
('Comfortable', 'Thoải mái', 'en', 'A2', 1, 'adjective', '/ˈkʌmftəbəl/', NULL),
('Dangerous', 'Nguy hiểm', 'en', 'A2', 1, 'adjective', '/ˈdeɪndʒərəs/', NULL),
('Government', 'Chính phủ', 'en', 'A2', 1, 'politics', '/ˈɡʌvərnmənt/', NULL),
('Hospital', 'Bệnh viện', 'en', 'A2', 1, 'place', '/ˈhɒspɪtəl/', NULL),
('Apartment', 'Căn hộ', 'en', 'A2', 1, 'place', '/əˈpɑːrtmənt/', NULL),
('Neighbor', 'Hàng xóm', 'en', 'A2', 1, 'people', '/ˈneɪbər/', NULL),
('Celebrate', 'Ăn mừng', 'en', 'A2', 1, 'action', '/ˈsɛlɪbreɪt/', NULL),
('Improve', 'Cải thiện', 'en', 'A2', 1, 'action', '/ɪmˈpruːv/', NULL),
('Explain', 'Giải thích', 'en', 'A2', 1, 'action', '/ɪkˈspleɪn/', NULL),
('Suddenly', 'Đột nhiên', 'en', 'A2', 1, 'adverb', '/ˈsʌdənli/', NULL),
('Perhaps', 'Có lẽ', 'en', 'A2', 1, 'adverb', '/pərˈhæps/', NULL),
('Necessary', 'Cần thiết', 'en', 'A2', 1, 'adjective', '/ˈnɛsəsɛri/', NULL),
('Opinion', 'Ý kiến', 'en', 'A2', 1, 'abstract', '/əˈpɪnjən/', NULL),
('Decision', 'Quyết định', 'en', 'A2', 1, 'abstract', '/dɪˈsɪʒən/', NULL),
('Advantage', 'Lợi thế', 'en', 'A2', 1, 'abstract', '/ədˈvɑːntɪdʒ/', NULL),
('Polite', 'Lịch sự', 'en', 'A2', 1, 'adjective', '/pəˈlaɪt/', NULL),
('Honest', 'Trung thực', 'en', 'A2', 1, 'adjective', '/ˈɒnɪst/', NULL),
('Nervous', 'Lo lắng', 'en', 'A2', 1, 'emotion', '/ˈnɜːrvəs/', NULL),
('Airport', 'Sân bay', 'en', 'A2', 1, 'place', '/ˈɛərpɔːrt/', NULL),
('Passport', 'Hộ chiếu', 'en', 'A2', 1, 'object', '/ˈpɑːspɔːrt/', NULL),
('Luggage', 'Hành lý', 'en', 'A2', 1, 'object', '/ˈlʌɡɪdʒ/', NULL),
('Ticket', 'Vé', 'en', 'A2', 1, 'object', '/ˈtɪkɪt/', NULL),
('Journey', 'Hành trình', 'en', 'A2', 1, 'travel', '/ˈdʒɜːrni/', NULL),
('Customer', 'Khách hàng', 'en', 'A2', 1, 'business', '/ˈkʌstəmər/', NULL),
('Interview', 'Phỏng vấn', 'en', 'A2', 1, 'business', '/ˈɪntərvjuː/', NULL),
('Salary', 'Lương', 'en', 'A2', 1, 'business', '/ˈsæləri/', NULL),
('Recipe', 'Công thức nấu ăn', 'en', 'A2', 1, 'food', '/ˈrɛsɪpi/', NULL),
('Delicious', 'Ngon', 'en', 'A2', 1, 'adjective', '/dɪˈlɪʃəs/', NULL),
('Healthy', 'Khỏe mạnh', 'en', 'A2', 1, 'adjective', '/ˈhɛlθi/', NULL),
('Exercise', 'Tập thể dục', 'en', 'A2', 1, 'action', '/ˈɛksərsaɪz/', NULL),
('Accident', 'Tai nạn', 'en', 'A2', 1, 'daily', '/ˈæksɪdənt/', NULL),
('Emergency', 'Khẩn cấp', 'en', 'A2', 1, 'daily', '/ɪˈmɜːrdʒənsi/', NULL),
('Disappointed', 'Thất vọng', 'en', 'A2', 1, 'emotion', '/ˌdɪsəˈpɔɪntɪd/', NULL),
('Excited', 'Hào hứng', 'en', 'A2', 1, 'emotion', '/ɪkˈsaɪtɪd/', NULL),
('Worried', 'Lo lắng', 'en', 'A2', 1, 'emotion', '/ˈwʌrid/', NULL),
('Generous', 'Hào phóng', 'en', 'A2', 1, 'adjective', '/ˈdʒɛnərəs/', NULL),
('Lazy', 'Lười biếng', 'en', 'A2', 1, 'adjective', '/ˈleɪzi/', NULL),
('Responsible', 'Có trách nhiệm', 'en', 'A2', 1, 'adjective', '/rɪˈspɒnsɪbəl/', NULL);

-- ============================================================
-- ENGLISH B1 (Intermediate) — 35 words, difficulty 2
-- ============================================================
INSERT INTO vocabularies (word, meaning, language, level, difficulty, category, ipa, pinyin) VALUES
('Consequence', 'Hậu quả', 'en', 'B1', 2, 'abstract', '/ˈkɒnsɪkwəns/', NULL),
('Negotiate', 'Thương lượng', 'en', 'B1', 2, 'action', '/nɪˈɡoʊʃieɪt/', NULL),
('Establish', 'Thiết lập', 'en', 'B1', 2, 'action', '/ɪˈstæblɪʃ/', NULL),
('Contribute', 'Đóng góp', 'en', 'B1', 2, 'action', '/kənˈtrɪbjuːt/', NULL),
('Significant', 'Quan trọng, đáng kể', 'en', 'B1', 2, 'adjective', '/sɪɡˈnɪfɪkənt/', NULL),
('Atmosphere', 'Bầu không khí', 'en', 'B1', 2, 'abstract', '/ˈætməsfɪər/', NULL),
('Confidence', 'Sự tự tin', 'en', 'B1', 2, 'abstract', '/ˈkɒnfɪdəns/', NULL),
('Persuade', 'Thuyết phục', 'en', 'B1', 2, 'action', '/pərˈsweɪd/', NULL),
('Influence', 'Ảnh hưởng', 'en', 'B1', 2, 'abstract', '/ˈɪnfluəns/', NULL),
('Opportunity', 'Cơ hội', 'en', 'B1', 2, 'abstract', '/ˌɒpəˈtjuːnɪti/', NULL),
('Development', 'Sự phát triển', 'en', 'B1', 2, 'abstract', '/dɪˈvɛləpmənt/', NULL),
('Population', 'Dân số', 'en', 'B1', 2, 'society', '/ˌpɒpjʊˈleɪʃən/', NULL),
('Environment', 'Môi trường', 'en', 'B1', 2, 'nature', '/ɪnˈvaɪrənmənt/', NULL),
('Temperature', 'Nhiệt độ', 'en', 'B1', 2, 'nature', '/ˈtɛmpərɪtʃər/', NULL),
('Achievement', 'Thành tựu', 'en', 'B1', 2, 'abstract', '/əˈtʃiːvmənt/', NULL),
('Investigate', 'Điều tra', 'en', 'B1', 2, 'action', '/ɪnˈvɛstɪɡeɪt/', NULL),
('Comparison', 'Sự so sánh', 'en', 'B1', 2, 'abstract', '/kəmˈpærɪsən/', NULL),
('Tradition', 'Truyền thống', 'en', 'B1', 2, 'culture', '/trəˈdɪʃən/', NULL),
('Reputation', 'Danh tiếng', 'en', 'B1', 2, 'abstract', '/ˌrɛpjʊˈteɪʃən/', NULL),
('Curriculum', 'Chương trình giảng dạy', 'en', 'B1', 2, 'education', '/kəˈrɪkjʊləm/', NULL),
('Manufacture', 'Sản xuất', 'en', 'B1', 2, 'business', '/ˌmænjʊˈfæktʃər/', NULL),
('Advertisement', 'Quảng cáo', 'en', 'B1', 2, 'business', '/ˌædvərˈtaɪzmənt/', NULL),
('Competition', 'Cuộc thi', 'en', 'B1', 2, 'abstract', '/ˌkɒmpɪˈtɪʃən/', NULL),
('Volunteer', 'Tình nguyện viên', 'en', 'B1', 2, 'people', '/ˌvɒlənˈtɪər/', NULL),
('Colleague', 'Đồng nghiệp', 'en', 'B1', 2, 'people', '/ˈkɒliːɡ/', NULL),
('Accurate', 'Chính xác', 'en', 'B1', 2, 'adjective', '/ˈækjərɪt/', NULL),
('Efficient', 'Hiệu quả', 'en', 'B1', 2, 'adjective', '/ɪˈfɪʃənt/', NULL),
('Enthusiasm', 'Sự nhiệt tình', 'en', 'B1', 2, 'emotion', '/ɪnˈθjuːziæzəm/', NULL),
('Agriculture', 'Nông nghiệp', 'en', 'B1', 2, 'nature', '/ˈæɡrɪkʌltʃər/', NULL),
('Pollution', 'Ô nhiễm', 'en', 'B1', 2, 'nature', '/pəˈluːʃən/', NULL),
('Earthquake', 'Động đất', 'en', 'B1', 2, 'nature', '/ˈɜːrθkweɪk/', NULL),
('Forecast', 'Dự báo', 'en', 'B1', 2, 'nature', '/ˈfɔːrkɑːst/', NULL),
('Recommend', 'Đề xuất', 'en', 'B1', 2, 'action', '/ˌrɛkəˈmɛnd/', NULL),
('Guarantee', 'Đảm bảo', 'en', 'B1', 2, 'action', '/ˌɡærənˈtiː/', NULL),
('Misunderstand', 'Hiểu nhầm', 'en', 'B1', 2, 'action', '/ˌmɪsʌndəˈstænd/', NULL);

-- ============================================================
-- ENGLISH B2 (Upper-Intermediate) — 35 words, difficulty 3
-- ============================================================
INSERT INTO vocabularies (word, meaning, language, level, difficulty, category, ipa, pinyin) VALUES
('Ambiguous', 'Mơ hồ, không rõ ràng', 'en', 'B2', 3, 'adjective', '/æmˈbɪɡjuəs/', NULL),
('Implications', 'Hàm ý, tác động', 'en', 'B2', 3, 'abstract', '/ˌɪmplɪˈkeɪʃənz/', NULL),
('Substantial', 'Đáng kể, quan trọng', 'en', 'B2', 3, 'adjective', '/səbˈstænʃəl/', NULL),
('Controversial', 'Gây tranh cãi', 'en', 'B2', 3, 'adjective', '/ˌkɒntrəˈvɜːrʃəl/', NULL),
('Phenomenon', 'Hiện tượng', 'en', 'B2', 3, 'abstract', '/fɪˈnɒmɪnɒn/', NULL),
('Comprehensive', 'Toàn diện', 'en', 'B2', 3, 'adjective', '/ˌkɒmprɪˈhɛnsɪv/', NULL),
('Deteriorate', 'Xuống cấp, xấu đi', 'en', 'B2', 3, 'action', '/dɪˈtɪəriəreɪt/', NULL),
('Simultaneously', 'Đồng thời', 'en', 'B2', 3, 'adverb', '/ˌsɪməlˈteɪniəsli/', NULL),
('Acknowledge', 'Thừa nhận', 'en', 'B2', 3, 'action', '/əkˈnɒlɪdʒ/', NULL),
('Accommodate', 'Đáp ứng, chứa', 'en', 'B2', 3, 'action', '/əˈkɒmədeɪt/', NULL),
('Bureaucracy', 'Bộ máy hành chính', 'en', 'B2', 3, 'politics', '/bjʊˈrɒkrəsi/', NULL),
('Hypothesis', 'Giả thuyết', 'en', 'B2', 3, 'science', '/haɪˈpɒθɪsɪs/', NULL),
('Infrastructure', 'Cơ sở hạ tầng', 'en', 'B2', 3, 'society', '/ˈɪnfrəstrʌktʃər/', NULL),
('Predominant', 'Chiếm ưu thế', 'en', 'B2', 3, 'adjective', '/prɪˈdɒmɪnənt/', NULL),
('Sustainability', 'Sự bền vững', 'en', 'B2', 3, 'abstract', '/səˌsteɪnəˈbɪlɪti/', NULL),
('Unprecedented', 'Chưa từng có', 'en', 'B2', 3, 'adjective', '/ʌnˈprɛsɪdɛntɪd/', NULL),
('Vulnerability', 'Tính dễ bị tổn thương', 'en', 'B2', 3, 'abstract', '/ˌvʌlnərəˈbɪlɪti/', NULL),
('Jurisdiction', 'Quyền tài phán', 'en', 'B2', 3, 'law', '/ˌdʒʊərɪsˈdɪkʃən/', NULL),
('Stakeholder', 'Bên liên quan', 'en', 'B2', 3, 'business', '/ˈsteɪkhoʊldər/', NULL),
('Consolidate', 'Củng cố', 'en', 'B2', 3, 'action', '/kənˈsɒlɪdeɪt/', NULL),
('Dilemma', 'Tình thế tiến thoái lưỡng nan', 'en', 'B2', 3, 'abstract', '/dɪˈlɛmə/', NULL),
('Empathy', 'Sự đồng cảm', 'en', 'B2', 3, 'emotion', '/ˈɛmpəθi/', NULL),
('Metaphor', 'Phép ẩn dụ', 'en', 'B2', 3, 'language', '/ˈmɛtəfɔːr/', NULL),
('Inevitable', 'Không thể tránh khỏi', 'en', 'B2', 3, 'adjective', '/ɪnˈɛvɪtəbəl/', NULL),
('Sophisticated', 'Tinh vi, phức tạp', 'en', 'B2', 3, 'adjective', '/səˈfɪstɪkeɪtɪd/', NULL),
('Prosperity', 'Sự thịnh vượng', 'en', 'B2', 3, 'abstract', '/prɒˈspɛrɪti/', NULL),
('Resilience', 'Sự kiên cường', 'en', 'B2', 3, 'abstract', '/rɪˈzɪliəns/', NULL),
('Discrimination', 'Phân biệt đối xử', 'en', 'B2', 3, 'society', '/dɪˌskrɪmɪˈneɪʃən/', NULL),
('Entrepreneur', 'Doanh nhân', 'en', 'B2', 3, 'business', '/ˌɒntrəprəˈnɜːr/', NULL),
('Innovation', 'Đổi mới sáng tạo', 'en', 'B2', 3, 'business', '/ˌɪnəˈveɪʃən/', NULL),
('Diplomacy', 'Ngoại giao', 'en', 'B2', 3, 'politics', '/dɪˈploʊməsi/', NULL),
('Propaganda', 'Tuyên truyền', 'en', 'B2', 3, 'politics', '/ˌprɒpəˈɡændə/', NULL),
('Testimony', 'Lời khai', 'en', 'B2', 3, 'law', '/ˈtɛstɪmoʊni/', NULL),
('Algorithm', 'Thuật toán', 'en', 'B2', 3, 'technology', '/ˈælɡərɪðəm/', NULL),
('Encryption', 'Mã hóa', 'en', 'B2', 3, 'technology', '/ɪnˈkrɪpʃən/', NULL);

-- ============================================================
-- ENGLISH C1 (Advanced) — 30 words, difficulty 3
-- ============================================================
INSERT INTO vocabularies (word, meaning, language, level, difficulty, category, ipa, pinyin) VALUES
('Albeit', 'Mặc dù, dẫu rằng', 'en', 'C1', 3, 'conjunction', '/ɔːlˈbiːɪt/', NULL),
('Ambivalent', 'Có tâm trạng lẫn lộn', 'en', 'C1', 3, 'adjective', '/æmˈbɪvələnt/', NULL),
('Articulate', 'Diễn đạt rõ ràng', 'en', 'C1', 3, 'action', '/ɑːrˈtɪkjʊleɪt/', NULL),
('Benevolent', 'Nhân từ, bác ái', 'en', 'C1', 3, 'adjective', '/bɪˈnɛvələnt/', NULL),
('Circumvent', 'Né tránh, vượt qua', 'en', 'C1', 3, 'action', '/ˌsɜːrkəmˈvɛnt/', NULL),
('Cognizant', 'Có ý thức, nhận thức được', 'en', 'C1', 3, 'adjective', '/ˈkɒɡnɪzənt/', NULL),
('Conjecture', 'Suy đoán', 'en', 'C1', 3, 'abstract', '/kənˈdʒɛktʃər/', NULL),
('Delineate', 'Phác thảo, mô tả rõ', 'en', 'C1', 3, 'action', '/dɪˈlɪnieɪt/', NULL),
('Deprecate', 'Phản đối, không khuyến khích', 'en', 'C1', 3, 'action', '/ˈdɛprɪkeɪt/', NULL),
('Discrepancy', 'Sự bất nhất, mâu thuẫn', 'en', 'C1', 3, 'abstract', '/dɪˈskrɛpənsi/', NULL),
('Eloquent', 'Hùng hồn, lưu loát', 'en', 'C1', 3, 'adjective', '/ˈɛləkwənt/', NULL),
('Equivocal', 'Nước đôi, mập mờ', 'en', 'C1', 3, 'adjective', '/ɪˈkwɪvəkəl/', NULL),
('Exacerbate', 'Làm trầm trọng thêm', 'en', 'C1', 3, 'action', '/ɪɡˈzæsərbeɪt/', NULL),
('Facilitate', 'Tạo điều kiện thuận lợi', 'en', 'C1', 3, 'action', '/fəˈsɪlɪteɪt/', NULL),
('Inherent', 'Vốn có, cố hữu', 'en', 'C1', 3, 'adjective', '/ɪnˈhɪərənt/', NULL),
('Meticulous', 'Tỉ mỉ, cẩn thận', 'en', 'C1', 3, 'adjective', '/mɪˈtɪkjʊləs/', NULL),
('Mitigation', 'Sự giảm nhẹ', 'en', 'C1', 3, 'abstract', '/ˌmɪtɪˈɡeɪʃən/', NULL),
('Nuance', 'Sắc thái, ý nghĩa tinh tế', 'en', 'C1', 3, 'abstract', '/ˈnjuːɑːns/', NULL),
('Paradigm', 'Mô hình, hệ thống tư duy', 'en', 'C1', 3, 'abstract', '/ˈpærədaɪm/', NULL),
('Pervasive', 'Lan tràn, thấm sâu', 'en', 'C1', 3, 'adjective', '/pərˈveɪsɪv/', NULL),
('Pragmatic', 'Thực dụng', 'en', 'C1', 3, 'adjective', '/præɡˈmætɪk/', NULL),
('Proliferate', 'Sinh sôi, lan rộng nhanh', 'en', 'C1', 3, 'action', '/prəˈlɪfəreɪt/', NULL),
('Reconcile', 'Hòa giải, dung hòa', 'en', 'C1', 3, 'action', '/ˈrɛkənsaɪl/', NULL),
('Scrutinize', 'Xem xét kỹ lưỡng', 'en', 'C1', 3, 'action', '/ˈskruːtɪnaɪz/', NULL),
('Tangible', 'Có thể cảm nhận được, hữu hình', 'en', 'C1', 3, 'adjective', '/ˈtændʒɪbəl/', NULL),
('Unequivocal', 'Dứt khoát, rõ ràng', 'en', 'C1', 3, 'adjective', '/ˌʌnɪˈkwɪvəkəl/', NULL),
('Vindicate', 'Minh oan, biện hộ', 'en', 'C1', 3, 'action', '/ˈvɪndɪkeɪt/', NULL),
('Corroborate', 'Xác nhận, củng cố bằng chứng', 'en', 'C1', 3, 'action', '/kəˈrɒbəreɪt/', NULL),
('Fluctuate', 'Dao động, biến động', 'en', 'C1', 3, 'action', '/ˈflʌktʃueɪt/', NULL),
('Hierarchy', 'Hệ thống phân cấp', 'en', 'C1', 3, 'abstract', '/ˈhaɪərɑːrki/', NULL);

-- ============================================================
-- ENGLISH C2 (Near-native mastery) — 25 words, difficulty 3
-- ============================================================
INSERT INTO vocabularies (word, meaning, language, level, difficulty, category, ipa, pinyin) VALUES
('Anachronism', 'Sự lỗi thời, điều không hợp thời', 'en', 'C2', 3, 'abstract', '/əˈnækrənɪzəm/', NULL),
('Apotheosis', 'Sự tôn vinh tột đỉnh, điển hình tiêu biểu', 'en', 'C2', 3, 'abstract', '/əˌpɒθiˈoʊsɪs/', NULL),
('Capricious', 'Thất thường, bất định', 'en', 'C2', 3, 'adjective', '/kəˈprɪʃəs/', NULL),
('Chicanery', 'Thủ đoạn lừa dối', 'en', 'C2', 3, 'abstract', '/ʃɪˈkeɪnəri/', NULL),
('Commensurate', 'Tương xứng, cân đối', 'en', 'C2', 3, 'adjective', '/kəˈmɛnʃərɪt/', NULL),
('Condescending', 'Kẻ cả, hạ cố', 'en', 'C2', 3, 'adjective', '/ˌkɒndɪˈsɛndɪŋ/', NULL),
('Diatribe', 'Bài chỉ trích gay gắt', 'en', 'C2', 3, 'abstract', '/ˈdaɪətraɪb/', NULL),
('Ebullient', 'Sôi nổi, nhiệt huyết', 'en', 'C2', 3, 'adjective', '/ɪˈbʌliənt/', NULL),
('Ephemeral', 'Chóng tàn, ngắn ngủi', 'en', 'C2', 3, 'adjective', '/ɪˈfɛmərəl/', NULL),
('Equanimity', 'Sự bình thản, điềm tĩnh', 'en', 'C2', 3, 'abstract', '/ˌiːkwəˈnɪmɪti/', NULL),
('Esoteric', 'Bí truyền, khó hiểu', 'en', 'C2', 3, 'adjective', '/ˌɛsəˈtɛrɪk/', NULL),
('Extemporaneous', 'Ứng khẩu, không chuẩn bị trước', 'en', 'C2', 3, 'adjective', '/ɪkˌstɛmpəˈreɪniəs/', NULL),
('Garrulous', 'Nhiều lời, lắm miệng', 'en', 'C2', 3, 'adjective', '/ˈɡærʊləs/', NULL),
('Hegemony', 'Quyền bá chủ, sự thống trị', 'en', 'C2', 3, 'abstract', '/hɪˈdʒɛməni/', NULL),
('Idiosyncratic', 'Đặc thù riêng của một người', 'en', 'C2', 3, 'adjective', '/ˌɪdiəsɪŋˈkrætɪk/', NULL),
('Impecunious', 'Túng thiếu, nghèo khó', 'en', 'C2', 3, 'adjective', '/ˌɪmpɪˈkjuːniəs/', NULL),
('Loquacious', 'Hay nói, ba hoa', 'en', 'C2', 3, 'adjective', '/loʊˈkweɪʃəs/', NULL),
('Magnanimous', 'Khoan dung, cao thượng', 'en', 'C2', 3, 'adjective', '/mæɡˈnænɪməs/', NULL),
('Mendacious', 'Hay nói dối, gian dối', 'en', 'C2', 3, 'adjective', '/mɛnˈdeɪʃəs/', NULL),
('Obfuscate', 'Làm mờ, che khuất sự thật', 'en', 'C2', 3, 'action', '/ˈɒbfʌskeɪt/', NULL),
('Perspicacious', 'Sáng suốt, nhạy bén', 'en', 'C2', 3, 'adjective', '/ˌpɜːrspɪˈkeɪʃəs/', NULL),
('Pernicious', 'Nguy hại, độc hại', 'en', 'C2', 3, 'adjective', '/pərˈnɪʃəs/', NULL),
('Recondite', 'Khó hiểu, uyên thâm', 'en', 'C2', 3, 'adjective', '/ˈrɛkəndaɪt/', NULL),
('Sycophant', 'Kẻ nịnh hót', 'en', 'C2', 3, 'people', '/ˈsɪkəfænt/', NULL),
('Tendentious', 'Có xu hướng thiên vị', 'en', 'C2', 3, 'adjective', '/tɛnˈdɛnʃəs/', NULL);

-- ============================================================
-- CHINESE HSK1 (Basic) — 40 words, difficulty 1
-- ============================================================
INSERT INTO vocabularies (word, meaning, language, level, difficulty, category, ipa, pinyin) VALUES
('你好', 'Xin chào', 'zh', 'HSK1', 1, 'greeting', NULL, 'nǐ hǎo'),
('谢谢', 'Cảm ơn', 'zh', 'HSK1', 1, 'greeting', NULL, 'xiè xiè'),
('再见', 'Tạm biệt', 'zh', 'HSK1', 1, 'greeting', NULL, 'zài jiàn'),
('学生', 'Học sinh', 'zh', 'HSK1', 1, 'people', NULL, 'xué shēng'),
('老师', 'Giáo viên', 'zh', 'HSK1', 1, 'people', NULL, 'lǎo shī'),
('中国', 'Trung Quốc', 'zh', 'HSK1', 1, 'place', NULL, 'zhōng guó'),
('朋友', 'Bạn bè', 'zh', 'HSK1', 1, 'people', NULL, 'péng yǒu'),
('家', 'Nhà', 'zh', 'HSK1', 1, 'place', NULL, 'jiā'),
('水', 'Nước', 'zh', 'HSK1', 1, 'food', NULL, 'shuǐ'),
('吃', 'Ăn', 'zh', 'HSK1', 1, 'action', NULL, 'chī'),
('喝', 'Uống', 'zh', 'HSK1', 1, 'action', NULL, 'hē'),
('大', 'To, lớn', 'zh', 'HSK1', 1, 'adjective', NULL, 'dà'),
('小', 'Nhỏ', 'zh', 'HSK1', 1, 'adjective', NULL, 'xiǎo'),
('高兴', 'Vui vẻ', 'zh', 'HSK1', 1, 'emotion', NULL, 'gāo xìng'),
('钱', 'Tiền', 'zh', 'HSK1', 1, 'object', NULL, 'qián'),
('书', 'Sách', 'zh', 'HSK1', 1, 'object', NULL, 'shū'),
('医院', 'Bệnh viện', 'zh', 'HSK1', 1, 'place', NULL, 'yī yuàn'),
('电脑', 'Máy tính', 'zh', 'HSK1', 1, 'object', NULL, 'diàn nǎo'),
('工作', 'Công việc', 'zh', 'HSK1', 1, 'daily', NULL, 'gōng zuò'),
('今天', 'Hôm nay', 'zh', 'HSK1', 1, 'time', NULL, 'jīn tiān'),
('猫', 'Con mèo', 'zh', 'HSK1', 1, 'animal', NULL, 'māo'),
('狗', 'Con chó', 'zh', 'HSK1', 1, 'animal', NULL, 'gǒu'),
('米饭', 'Cơm', 'zh', 'HSK1', 1, 'food', NULL, 'mǐ fàn'),
('茶', 'Trà', 'zh', 'HSK1', 1, 'food', NULL, 'chá'),
('苹果', 'Quả táo', 'zh', 'HSK1', 1, 'food', NULL, 'píng guǒ'),
('妈妈', 'Mẹ', 'zh', 'HSK1', 1, 'people', NULL, 'mā ma'),
('爸爸', 'Bố', 'zh', 'HSK1', 1, 'people', NULL, 'bà ba'),
('哥哥', 'Anh trai', 'zh', 'HSK1', 1, 'people', NULL, 'gē ge'),
('姐姐', 'Chị gái', 'zh', 'HSK1', 1, 'people', NULL, 'jiě jiě'),
('飞机', 'Máy bay', 'zh', 'HSK1', 1, 'object', NULL, 'fēi jī'),
('出租车', 'Xe tắc xi', 'zh', 'HSK1', 1, 'object', NULL, 'chū zū chē'),
('下雨', 'Trời mưa', 'zh', 'HSK1', 1, 'weather', NULL, 'xià yǔ'),
('天气', 'Thời tiết', 'zh', 'HSK1', 1, 'weather', NULL, 'tiān qì'),
('漂亮', 'Đẹp', 'zh', 'HSK1', 1, 'adjective', NULL, 'piào liàng'),
('快', 'Nhanh', 'zh', 'HSK1', 1, 'adjective', NULL, 'kuài'),
('慢', 'Chậm', 'zh', 'HSK1', 1, 'adjective', NULL, 'màn'),
('冷', 'Lạnh', 'zh', 'HSK1', 1, 'adjective', NULL, 'lěng'),
('热', 'Nóng', 'zh', 'HSK1', 1, 'adjective', NULL, 'rè'),
('人', 'Người', 'zh', 'HSK1', 1, 'people', NULL, 'rén'),
('月', 'Tháng, mặt trăng', 'zh', 'HSK1', 1, 'time', NULL, 'yuè');

-- ============================================================
-- CHINESE HSK2 (Elementary) — 35 words, difficulty 1
-- ============================================================
INSERT INTO vocabularies (word, meaning, language, level, difficulty, category, ipa, pinyin) VALUES
('准备', 'Chuẩn bị', 'zh', 'HSK2', 1, 'action', NULL, 'zhǔn bèi'),
('已经', 'Đã rồi', 'zh', 'HSK2', 1, 'adverb', NULL, 'yǐ jīng'),
('虽然', 'Mặc dù', 'zh', 'HSK2', 1, 'conjunction', NULL, 'suī rán'),
('公司', 'Công ty', 'zh', 'HSK2', 1, 'place', NULL, 'gōng sī'),
('一直', 'Luôn luôn', 'zh', 'HSK2', 1, 'adverb', NULL, 'yī zhí'),
('生日', 'Sinh nhật', 'zh', 'HSK2', 1, 'daily', NULL, 'shēng rì'),
('历史', 'Lịch sử', 'zh', 'HSK2', 1, 'education', NULL, 'lì shǐ'),
('健康', 'Sức khỏe', 'zh', 'HSK2', 1, 'daily', NULL, 'jiàn kāng'),
('练习', 'Luyện tập', 'zh', 'HSK2', 1, 'action', NULL, 'liàn xí'),
('帮助', 'Giúp đỡ', 'zh', 'HSK2', 1, 'action', NULL, 'bāng zhù'),
('认为', 'Cho rằng', 'zh', 'HSK2', 1, 'action', NULL, 'rèn wéi'),
('关系', 'Mối quan hệ', 'zh', 'HSK2', 1, 'abstract', NULL, 'guān xì'),
('环境', 'Môi trường', 'zh', 'HSK2', 1, 'nature', NULL, 'huán jìng'),
('解决', 'Giải quyết', 'zh', 'HSK2', 1, 'action', NULL, 'jiě jué'),
('机会', 'Cơ hội', 'zh', 'HSK2', 1, 'abstract', NULL, 'jī huì'),
('简单', 'Đơn giản', 'zh', 'HSK2', 1, 'adjective', NULL, 'jiǎn dān'),
('复杂', 'Phức tạp', 'zh', 'HSK2', 1, 'adjective', NULL, 'fù zá'),
('聪明', 'Thông minh', 'zh', 'HSK2', 1, 'adjective', NULL, 'cōng míng'),
('努力', 'Nỗ lực', 'zh', 'HSK2', 1, 'adjective', NULL, 'nǔ lì'),
('方便', 'Thuận tiện', 'zh', 'HSK2', 1, 'adjective', NULL, 'fāng biàn'),
('安全', 'An toàn', 'zh', 'HSK2', 1, 'adjective', NULL, 'ān quán'),
('着急', 'Nóng lòng', 'zh', 'HSK2', 1, 'emotion', NULL, 'zháo jí'),
('担心', 'Lo lắng', 'zh', 'HSK2', 1, 'emotion', NULL, 'dān xīn'),
('满意', 'Hài lòng', 'zh', 'HSK2', 1, 'emotion', NULL, 'mǎn yì'),
('超市', 'Siêu thị', 'zh', 'HSK2', 1, 'place', NULL, 'chāo shì'),
('银行', 'Ngân hàng', 'zh', 'HSK2', 1, 'place', NULL, 'yín háng'),
('护照', 'Hộ chiếu', 'zh', 'HSK2', 1, 'object', NULL, 'hù zhào'),
('行李', 'Hành lý', 'zh', 'HSK2', 1, 'object', NULL, 'xíng lǐ'),
('地铁', 'Tàu điện ngầm', 'zh', 'HSK2', 1, 'object', NULL, 'dì tiě'),
('邻居', 'Hàng xóm', 'zh', 'HSK2', 1, 'people', NULL, 'lín jū'),
('同事', 'Đồng nghiệp', 'zh', 'HSK2', 1, 'people', NULL, 'tóng shì'),
('客人', 'Khách mời', 'zh', 'HSK2', 1, 'people', NULL, 'kè rén'),
('礼物', 'Quà tặng', 'zh', 'HSK2', 1, 'object', NULL, 'lǐ wù'),
('季节', 'Mùa', 'zh', 'HSK2', 1, 'time', NULL, 'jì jié'),
('春天', 'Mùa xuân', 'zh', 'HSK2', 1, 'time', NULL, 'chūn tiān');

-- ============================================================
-- CHINESE HSK3 (Intermediate) — 35 words, difficulty 2
-- ============================================================
INSERT INTO vocabularies (word, meaning, language, level, difficulty, category, ipa, pinyin) VALUES
('经验', 'Kinh nghiệm', 'zh', 'HSK3', 2, 'abstract', NULL, 'jīng yàn'),
('丰富', 'Phong phú', 'zh', 'HSK3', 2, 'adjective', NULL, 'fēng fù'),
('信用卡', 'Thẻ tín dụng', 'zh', 'HSK3', 2, 'object', NULL, 'xìn yòng kǎ'),
('性格', 'Tính cách', 'zh', 'HSK3', 2, 'abstract', NULL, 'xìng gé'),
('交流', 'Giao lưu, trao đổi', 'zh', 'HSK3', 2, 'action', NULL, 'jiāo liú'),
('传统', 'Truyền thống', 'zh', 'HSK3', 2, 'culture', NULL, 'chuán tǒng'),
('观众', 'Khán giả', 'zh', 'HSK3', 2, 'people', NULL, 'guān zhòng'),
('科技', 'Khoa học công nghệ', 'zh', 'HSK3', 2, 'science', NULL, 'kē jì'),
('责任', 'Trách nhiệm', 'zh', 'HSK3', 2, 'abstract', NULL, 'zé rèn'),
('竞争', 'Cạnh tranh', 'zh', 'HSK3', 2, 'abstract', NULL, 'jìng zhēng'),
('优秀', 'Xuất sắc', 'zh', 'HSK3', 2, 'adjective', NULL, 'yōu xiù'),
('积极', 'Tích cực', 'zh', 'HSK3', 2, 'adjective', NULL, 'jī jí'),
('氛围', 'Bầu không khí', 'zh', 'HSK3', 2, 'abstract', NULL, 'fēn wéi'),
('效率', 'Hiệu suất', 'zh', 'HSK3', 2, 'abstract', NULL, 'xiào lǜ'),
('挑战', 'Thử thách', 'zh', 'HSK3', 2, 'abstract', NULL, 'tiǎo zhàn'),
('合适', 'Phù hợp', 'zh', 'HSK3', 2, 'adjective', NULL, 'hé shì'),
('印象', 'Ấn tượng', 'zh', 'HSK3', 2, 'abstract', NULL, 'yìn xiàng'),
('建议', 'Đề nghị, gợi ý', 'zh', 'HSK3', 2, 'action', NULL, 'jiàn yì'),
('发展', 'Phát triển', 'zh', 'HSK3', 2, 'abstract', NULL, 'fā zhǎn'),
('政策', 'Chính sách', 'zh', 'HSK3', 2, 'politics', NULL, 'zhèng cè'),
('收入', 'Thu nhập', 'zh', 'HSK3', 2, 'business', NULL, 'shōu rù'),
('消费', 'Tiêu dùng', 'zh', 'HSK3', 2, 'business', NULL, 'xiāo fèi'),
('广告', 'Quảng cáo', 'zh', 'HSK3', 2, 'business', NULL, 'guǎng gào'),
('节约', 'Tiết kiệm', 'zh', 'HSK3', 2, 'action', NULL, 'jié yuē'),
('污染', 'Ô nhiễm', 'zh', 'HSK3', 2, 'nature', NULL, 'wū rǎn'),
('保护', 'Bảo vệ', 'zh', 'HSK3', 2, 'action', NULL, 'bǎo hù'),
('温度', 'Nhiệt độ', 'zh', 'HSK3', 2, 'nature', NULL, 'wēn dù'),
('地震', 'Động đất', 'zh', 'HSK3', 2, 'nature', NULL, 'dì zhèn'),
('教育', 'Giáo dục', 'zh', 'HSK3', 2, 'education', NULL, 'jiào yù'),
('毕业', 'Tốt nghiệp', 'zh', 'HSK3', 2, 'education', NULL, 'bì yè'),
('奖学金', 'Học bổng', 'zh', 'HSK3', 2, 'education', NULL, 'jiǎng xué jīn'),
('失败', 'Thất bại', 'zh', 'HSK3', 2, 'abstract', NULL, 'shī bài'),
('成功', 'Thành công', 'zh', 'HSK3', 2, 'abstract', NULL, 'chéng gōng'),
('勇敢', 'Dũng cảm', 'zh', 'HSK3', 2, 'adjective', NULL, 'yǒng gǎn'),
('骄傲', 'Tự hào', 'zh', 'HSK3', 2, 'emotion', NULL, 'jiāo ào');

-- ============================================================
-- CHINESE HSK4 (Upper-Intermediate) — 30 words, difficulty 2
-- ============================================================
INSERT INTO vocabularies (word, meaning, language, level, difficulty, category, ipa, pinyin) VALUES
('尽管', 'Mặc dù, dù cho', 'zh', 'HSK4', 2, 'conjunction', NULL, 'jǐn guǎn'),
('逐渐', 'Dần dần', 'zh', 'HSK4', 2, 'adverb', NULL, 'zhú jiàn'),
('影响', 'Ảnh hưởng', 'zh', 'HSK4', 2, 'abstract', NULL, 'yǐng xiǎng'),
('态度', 'Thái độ', 'zh', 'HSK4', 2, 'abstract', NULL, 'tài dù'),
('目标', 'Mục tiêu', 'zh', 'HSK4', 2, 'abstract', NULL, 'mù biāo'),
('压力', 'Áp lực', 'zh', 'HSK4', 2, 'abstract', NULL, 'yā lì'),
('认识', 'Nhận ra, quen biết', 'zh', 'HSK4', 2, 'action', NULL, 'rèn shi'),
('提高', 'Nâng cao, cải thiện', 'zh', 'HSK4', 2, 'action', NULL, 'tí gāo'),
('表达', 'Biểu đạt, diễn đạt', 'zh', 'HSK4', 2, 'action', NULL, 'biǎo dá'),
('分析', 'Phân tích', 'zh', 'HSK4', 2, 'action', NULL, 'fēn xī'),
('讨论', 'Thảo luận', 'zh', 'HSK4', 2, 'action', NULL, 'tǎo lùn'),
('理解', 'Hiểu, lĩnh hội', 'zh', 'HSK4', 2, 'action', NULL, 'lǐ jiě'),
('调查', 'Điều tra, khảo sát', 'zh', 'HSK4', 2, 'action', NULL, 'diào chá'),
('合作', 'Hợp tác', 'zh', 'HSK4', 2, 'action', NULL, 'hé zuò'),
('参加', 'Tham gia', 'zh', 'HSK4', 2, 'action', NULL, 'cān jiā'),
('文化', 'Văn hóa', 'zh', 'HSK4', 2, 'culture', NULL, 'wén huà'),
('经济', 'Kinh tế', 'zh', 'HSK4', 2, 'business', NULL, 'jīng jì'),
('社会', 'Xã hội', 'zh', 'HSK4', 2, 'society', NULL, 'shè huì'),
('法律', 'Pháp luật', 'zh', 'HSK4', 2, 'law', NULL, 'fǎ lǜ'),
('医疗', 'Y tế', 'zh', 'HSK4', 2, 'daily', NULL, 'yī liáo'),
('环保', 'Bảo vệ môi trường', 'zh', 'HSK4', 2, 'nature', NULL, 'huán bǎo'),
('资源', 'Tài nguyên', 'zh', 'HSK4', 2, 'nature', NULL, 'zī yuán'),
('能源', 'Năng lượng', 'zh', 'HSK4', 2, 'science', NULL, 'néng yuán'),
('技术', 'Kỹ thuật, công nghệ', 'zh', 'HSK4', 2, 'science', NULL, 'jì shù'),
('网络', 'Mạng lưới, internet', 'zh', 'HSK4', 2, 'technology', NULL, 'wǎng luò'),
('平等', 'Bình đẳng', 'zh', 'HSK4', 2, 'society', NULL, 'píng děng'),
('尊重', 'Tôn trọng', 'zh', 'HSK4', 2, 'abstract', NULL, 'zūn zhòng'),
('解释', 'Giải thích', 'zh', 'HSK4', 2, 'action', NULL, 'jiě shì'),
('预防', 'Phòng ngừa', 'zh', 'HSK4', 2, 'action', NULL, 'yù fáng'),
('改变', 'Thay đổi', 'zh', 'HSK4', 2, 'action', NULL, 'gǎi biàn');

-- ============================================================
-- CHINESE HSK5 (Advanced) — 25 words, difficulty 3
-- ============================================================
INSERT INTO vocabularies (word, meaning, language, level, difficulty, category, ipa, pinyin) VALUES
('抽象', 'Trừu tượng', 'zh', 'HSK5', 3, 'abstract', NULL, 'chōu xiàng'),
('辩证', 'Biện chứng', 'zh', 'HSK5', 3, 'abstract', NULL, 'biàn zhèng'),
('矛盾', 'Mâu thuẫn', 'zh', 'HSK5', 3, 'abstract', NULL, 'máo dùn'),
('利益', 'Lợi ích', 'zh', 'HSK5', 3, 'abstract', NULL, 'lì yì'),
('妥协', 'Thỏa hiệp, nhượng bộ', 'zh', 'HSK5', 3, 'action', NULL, 'tuǒ xié'),
('争议', 'Tranh cãi, tranh chấp', 'zh', 'HSK5', 3, 'abstract', NULL, 'zhēng yì'),
('歧视', 'Phân biệt đối xử', 'zh', 'HSK5', 3, 'society', NULL, 'qí shì'),
('腐败', 'Tham nhũng, hư hỏng', 'zh', 'HSK5', 3, 'politics', NULL, 'fǔ bài'),
('监督', 'Giám sát', 'zh', 'HSK5', 3, 'action', NULL, 'jiān dū'),
('透明', 'Minh bạch, trong suốt', 'zh', 'HSK5', 3, 'adjective', NULL, 'tòu míng'),
('批判', 'Phê phán', 'zh', 'HSK5', 3, 'action', NULL, 'pī pàn'),
('推动', 'Thúc đẩy', 'zh', 'HSK5', 3, 'action', NULL, 'tuī dòng'),
('反映', 'Phản ánh', 'zh', 'HSK5', 3, 'action', NULL, 'fǎn yìng'),
('创新', 'Đổi mới sáng tạo', 'zh', 'HSK5', 3, 'abstract', NULL, 'chuàng xīn'),
('全球化', 'Toàn cầu hóa', 'zh', 'HSK5', 3, 'society', NULL, 'quán qiú huà'),
('可持续', 'Bền vững', 'zh', 'HSK5', 3, 'abstract', NULL, 'kě chí xù'),
('人工智能', 'Trí tuệ nhân tạo', 'zh', 'HSK5', 3, 'technology', NULL, 'rén gōng zhì néng'),
('大数据', 'Dữ liệu lớn', 'zh', 'HSK5', 3, 'technology', NULL, 'dà shù jù'),
('舆论', 'Dư luận', 'zh', 'HSK5', 3, 'society', NULL, 'yú lùn'),
('伦理', 'Đạo đức, luân lý', 'zh', 'HSK5', 3, 'abstract', NULL, 'lún lǐ'),
('隐私', 'Quyền riêng tư', 'zh', 'HSK5', 3, 'abstract', NULL, 'yǐn sī'),
('版权', 'Bản quyền', 'zh', 'HSK5', 3, 'law', NULL, 'bǎn quán'),
('主权', 'Chủ quyền', 'zh', 'HSK5', 3, 'politics', NULL, 'zhǔ quán'),
('博弈', 'Cạnh tranh chiến lược, đấu trí', 'zh', 'HSK5', 3, 'abstract', NULL, 'bó yì'),
('顿悟', 'Sự giác ngộ đột ngột, bừng tỉnh', 'zh', 'HSK5', 3, 'abstract', NULL, 'dùn wù');
