-- Seed common vocabulary words organized by CEFR (English) and HSK (Chinese) levels
-- Replace any existing seed data
DELETE FROM vocabularies;

-- English A1 (Beginner - Basic words)
INSERT INTO vocabularies (word, meaning, language, level, difficulty, category) VALUES
('Hello', 'Xin chào', 'en', 'A1', 1, 'greeting'),
('Goodbye', 'Tạm biệt', 'en', 'A1', 1, 'greeting'),
('Thank you', 'Cảm ơn', 'en', 'A1', 1, 'greeting'),
('Please', 'Làm ơn', 'en', 'A1', 1, 'greeting'),
('Water', 'Nước', 'en', 'A1', 1, 'food'),
('Food', 'Thức ăn', 'en', 'A1', 1, 'food'),
('House', 'Ngôi nhà', 'en', 'A1', 1, 'place'),
('School', 'Trường học', 'en', 'A1', 1, 'place'),
('Family', 'Gia đình', 'en', 'A1', 1, 'people'),
('Friend', 'Bạn bè', 'en', 'A1', 1, 'people'),
('Book', 'Quyển sách', 'en', 'A1', 1, 'object'),
('Teacher', 'Giáo viên', 'en', 'A1', 1, 'people'),
('Student', 'Học sinh', 'en', 'A1', 1, 'people'),
('Morning', 'Buổi sáng', 'en', 'A1', 1, 'time'),
('Night', 'Buổi tối', 'en', 'A1', 1, 'time'),
('Happy', 'Vui vẻ', 'en', 'A1', 1, 'emotion'),
('Beautiful', 'Đẹp', 'en', 'A1', 1, 'adjective'),
('Big', 'To, lớn', 'en', 'A1', 1, 'adjective'),
('Small', 'Nhỏ', 'en', 'A1', 1, 'adjective'),
('Money', 'Tiền', 'en', 'A1', 1, 'object');

-- English A2 (Elementary)
INSERT INTO vocabularies (word, meaning, language, level, difficulty, category) VALUES
('Appointment', 'Cuộc hẹn', 'en', 'A2', 1, 'daily'),
('Experience', 'Kinh nghiệm', 'en', 'A2', 1, 'abstract'),
('Comfortable', 'Thoải mái', 'en', 'A2', 1, 'adjective'),
('Dangerous', 'Nguy hiểm', 'en', 'A2', 1, 'adjective'),
('Government', 'Chính phủ', 'en', 'A2', 1, 'politics'),
('Hospital', 'Bệnh viện', 'en', 'A2', 1, 'place'),
('Apartment', 'Căn hộ', 'en', 'A2', 1, 'place'),
('Neighbor', 'Hàng xóm', 'en', 'A2', 1, 'people'),
('Celebrate', 'Kỷ niệm, ăn mừng', 'en', 'A2', 1, 'action'),
('Improve', 'Cải thiện', 'en', 'A2', 1, 'action'),
('Explain', 'Giải thích', 'en', 'A2', 1, 'action'),
('Suddenly', 'Đột nhiên', 'en', 'A2', 1, 'adverb'),
('Perhaps', 'Có lẽ', 'en', 'A2', 1, 'adverb'),
('Necessary', 'Cần thiết', 'en', 'A2', 1, 'adjective'),
('Opinion', 'Ý kiến', 'en', 'A2', 1, 'abstract'),
('Decision', 'Quyết định', 'en', 'A2', 1, 'abstract'),
('Advantage', 'Lợi thế', 'en', 'A2', 1, 'abstract'),
('Polite', 'Lịch sự', 'en', 'A2', 1, 'adjective'),
('Honest', 'Trung thực', 'en', 'A2', 1, 'adjective'),
('Nervous', 'Lo lắng', 'en', 'A2', 1, 'emotion');

-- English B1 (Intermediate)
INSERT INTO vocabularies (word, meaning, language, level, difficulty, category) VALUES
('Consequence', 'Hậu quả', 'en', 'B1', 2, 'abstract'),
('Negotiate', 'Thương lượng', 'en', 'B1', 2, 'action'),
('Establish', 'Thiết lập', 'en', 'B1', 2, 'action'),
('Contribute', 'Đóng góp', 'en', 'B1', 2, 'action'),
('Significant', 'Quan trọng, đáng kể', 'en', 'B1', 2, 'adjective'),
('Atmosphere', 'Bầu không khí', 'en', 'B1', 2, 'abstract'),
('Confidence', 'Sự tự tin', 'en', 'B1', 2, 'abstract'),
('Persuade', 'Thuyết phục', 'en', 'B1', 2, 'action'),
('Influence', 'Ảnh hưởng', 'en', 'B1', 2, 'abstract'),
('Opportunity', 'Cơ hội', 'en', 'B1', 2, 'abstract'),
('Development', 'Sự phát triển', 'en', 'B1', 2, 'abstract'),
('Population', 'Dân số', 'en', 'B1', 2, 'society'),
('Environment', 'Môi trường', 'en', 'B1', 2, 'nature'),
('Temperature', 'Nhiệt độ', 'en', 'B1', 2, 'nature'),
('Achievement', 'Thành tựu', 'en', 'B1', 2, 'abstract'),
('Investigate', 'Điều tra', 'en', 'B1', 2, 'action'),
('Comparison', 'Sự so sánh', 'en', 'B1', 2, 'abstract'),
('Tradition', 'Truyền thống', 'en', 'B1', 2, 'culture'),
('Reputation', 'Danh tiếng', 'en', 'B1', 2, 'abstract'),
('Curriculum', 'Chương trình giảng dạy', 'en', 'B1', 2, 'education');

-- English B2 (Upper Intermediate)
INSERT INTO vocabularies (word, meaning, language, level, difficulty, category) VALUES
('Ambiguous', 'Mơ hồ, không rõ ràng', 'en', 'B2', 3, 'adjective'),
('Implications', 'Hàm ý, tác động', 'en', 'B2', 3, 'abstract'),
('Substantial', 'Đáng kể, quan trọng', 'en', 'B2', 3, 'adjective'),
('Controversial', 'Gây tranh cãi', 'en', 'B2', 3, 'adjective'),
('Phenomenon', 'Hiện tượng', 'en', 'B2', 3, 'abstract'),
('Comprehensive', 'Toàn diện', 'en', 'B2', 3, 'adjective'),
('Deteriorate', 'Xuống cấp, xấu đi', 'en', 'B2', 3, 'action'),
('Simultaneously', 'Đồng thời', 'en', 'B2', 3, 'adverb'),
('Acknowledge', 'Thừa nhận', 'en', 'B2', 3, 'action'),
('Accommodate', 'Đáp ứng, chứa', 'en', 'B2', 3, 'action'),
('Bureaucracy', 'Bộ máy hành chính', 'en', 'B2', 3, 'politics'),
('Hypothesis', 'Giả thuyết', 'en', 'B2', 3, 'science'),
('Infrastructure', 'Cơ sở hạ tầng', 'en', 'B2', 3, 'society'),
('Predominant', 'Chiếm ưu thế', 'en', 'B2', 3, 'adjective'),
('Sustainability', 'Sự bền vững', 'en', 'B2', 3, 'abstract'),
('Unprecedented', 'Chưa từng có', 'en', 'B2', 3, 'adjective'),
('Vulnerability', 'Tính dễ bị tổn thương', 'en', 'B2', 3, 'abstract'),
('Jurisdiction', 'Quyền tài phán', 'en', 'B2', 3, 'law'),
('Stakeholder', 'Bên liên quan', 'en', 'B2', 3, 'business'),
('Consolidate', 'Củng cố', 'en', 'B2', 3, 'action');

-- Chinese HSK1 (Basic)
INSERT INTO vocabularies (word, meaning, language, level, difficulty, category) VALUES
('你好', 'Xin chào', 'zh', 'HSK1', 1, 'greeting'),
('谢谢', 'Cảm ơn', 'zh', 'HSK1', 1, 'greeting'),
('再见', 'Tạm biệt', 'zh', 'HSK1', 1, 'greeting'),
('学生', 'Học sinh', 'zh', 'HSK1', 1, 'people'),
('老师', 'Giáo viên', 'zh', 'HSK1', 1, 'people'),
('中国', 'Trung Quốc', 'zh', 'HSK1', 1, 'place'),
('朋友', 'Bạn bè', 'zh', 'HSK1', 1, 'people'),
('家', 'Nhà', 'zh', 'HSK1', 1, 'place'),
('水', 'Nước', 'zh', 'HSK1', 1, 'food'),
('吃', 'Ăn', 'zh', 'HSK1', 1, 'action'),
('喝', 'Uống', 'zh', 'HSK1', 1, 'action'),
('大', 'To, lớn', 'zh', 'HSK1', 1, 'adjective'),
('小', 'Nhỏ', 'zh', 'HSK1', 1, 'adjective'),
('高兴', 'Vui vẻ', 'zh', 'HSK1', 1, 'emotion'),
('钱', 'Tiền', 'zh', 'HSK1', 1, 'object'),
('书', 'Sách', 'zh', 'HSK1', 1, 'object'),
('医院', 'Bệnh viện', 'zh', 'HSK1', 1, 'place'),
('电脑', 'Máy tính', 'zh', 'HSK1', 1, 'object'),
('工作', 'Công việc', 'zh', 'HSK1', 1, 'daily'),
('今天', 'Hôm nay', 'zh', 'HSK1', 1, 'time');

-- Chinese HSK2 (Elementary)
INSERT INTO vocabularies (word, meaning, language, level, difficulty, category) VALUES
('准备', 'Chuẩn bị', 'zh', 'HSK2', 1, 'action'),
('已经', 'Đã (rồi)', 'zh', 'HSK2', 1, 'adverb'),
('虽然', 'Mặc dù', 'zh', 'HSK2', 1, 'conjunction'),
('公司', 'Công ty', 'zh', 'HSK2', 1, 'place'),
('一直', 'Luôn luôn', 'zh', 'HSK2', 1, 'adverb'),
('生日', 'Sinh nhật', 'zh', 'HSK2', 1, 'daily'),
('历史', 'Lịch sử', 'zh', 'HSK2', 1, 'education'),
('健康', 'Sức khỏe', 'zh', 'HSK2', 1, 'daily'),
('练习', 'Luyện tập', 'zh', 'HSK2', 1, 'action'),
('帮助', 'Giúp đỡ', 'zh', 'HSK2', 1, 'action'),
('认为', 'Cho rằng', 'zh', 'HSK2', 1, 'action'),
('关系', 'Mối quan hệ', 'zh', 'HSK2', 1, 'abstract'),
('环境', 'Môi trường', 'zh', 'HSK2', 1, 'nature'),
('解决', 'Giải quyết', 'zh', 'HSK2', 1, 'action'),
('机会', 'Cơ hội', 'zh', 'HSK2', 1, 'abstract'),
('简单', 'Đơn giản', 'zh', 'HSK2', 1, 'adjective'),
('复杂', 'Phức tạp', 'zh', 'HSK2', 2, 'adjective'),
('聪明', 'Thông minh', 'zh', 'HSK2', 1, 'adjective'),
('努力', 'Nỗ lực', 'zh', 'HSK2', 1, 'adjective'),
('方便', 'Thuận tiện', 'zh', 'HSK2', 1, 'adjective');

-- Chinese HSK3 (Intermediate)
INSERT INTO vocabularies (word, meaning, language, level, difficulty, category) VALUES
('经验', 'Kinh nghiệm', 'zh', 'HSK3', 2, 'abstract'),
('丰富', 'Phong phú', 'zh', 'HSK3', 2, 'adjective'),
('信用卡', 'Thẻ tín dụng', 'zh', 'HSK3', 2, 'object'),
('性格', 'Tính cách', 'zh', 'HSK3', 2, 'abstract'),
('交流', 'Giao lưu, trao đổi', 'zh', 'HSK3', 2, 'action'),
('传统', 'Truyền thống', 'zh', 'HSK3', 2, 'culture'),
('观众', 'Khán giả', 'zh', 'HSK3', 2, 'people'),
('科技', 'Khoa học công nghệ', 'zh', 'HSK3', 2, 'science'),
('责任', 'Trách nhiệm', 'zh', 'HSK3', 2, 'abstract'),
('竞争', 'Cạnh tranh', 'zh', 'HSK3', 2, 'abstract'),
('优秀', 'Ưu tú, xuất sắc', 'zh', 'HSK3', 2, 'adjective'),
('积极', 'Tích cực', 'zh', 'HSK3', 2, 'adjective'),
('氛围', 'Bầu không khí', 'zh', 'HSK3', 2, 'abstract'),
('效率', 'Hiệu suất', 'zh', 'HSK3', 2, 'abstract'),
('挑战', 'Thử thách', 'zh', 'HSK3', 2, 'abstract'),
('合适', 'Phù hợp', 'zh', 'HSK3', 2, 'adjective'),
('印象', 'Ấn tượng', 'zh', 'HSK3', 2, 'abstract'),
('建议', 'Đề nghị, gợi ý', 'zh', 'HSK3', 2, 'action'),
('发展', 'Phát triển', 'zh', 'HSK3', 2, 'abstract'),
('政策', 'Chính sách', 'zh', 'HSK3', 2, 'politics');
