-- 006_update_definitions.sql
-- Auto-generated definitions for existing English vocabulary

UPDATE vocabularies SET definition = '"Hello!" or an equivalent greeting.' WHERE word = 'Hello' AND language = 'en';
UPDATE vocabularies SET definition = 'An utterance of goodbye, the wishing of farewell to someone.' WHERE word = 'Goodbye' AND language = 'en';
UPDATE vocabularies SET definition = 'An expression of gratitude or politeness in response to something done or given.' WHERE word = 'Thank you' AND language = 'en';
UPDATE vocabularies SET definition = 'To make happy or satisfy; to give pleasure to.' WHERE word = 'Please' AND language = 'en';
UPDATE vocabularies SET definition = 'A substance (of molecular formula H₂O) found at room temperature and pressure as a clear liquid; it is present naturally as rain, and found in rivers, lakes and seas; its solid form is ice and its gaseous form is steam.' WHERE word = 'Water' AND language = 'en';
UPDATE vocabularies SET definition = 'Any solid substance that can be consumed by living organisms, especially by eating, in order to sustain life.' WHERE word = 'Food' AND language = 'en';
UPDATE vocabularies SET definition = 'A structure built or serving as an abode of human beings.' WHERE word = 'House' AND language = 'en';
UPDATE vocabularies SET definition = '(collective) A group of fish or a group of marine mammals such as porpoises, dolphins, or whales.' WHERE word = 'School' AND language = 'en';
UPDATE vocabularies SET definition = 'A group of people who are closely related to one another (by blood, marriage or adoption); kin; for example, a set of parents and their children; an immediate family.' WHERE word = 'Family' AND language = 'en';
UPDATE vocabularies SET definition = 'A person other than a family member, spouse or lover whose company one enjoys and towards whom one feels affection.' WHERE word = 'Friend' AND language = 'en';
UPDATE vocabularies SET definition = 'A collection of sheets of paper bound together to hinge at one edge, containing printed or written material, pictures, etc.' WHERE word = 'Book' AND language = 'en';
UPDATE vocabularies SET definition = 'A person who teaches, especially one employed in a school.' WHERE word = 'Teacher' AND language = 'en';
UPDATE vocabularies SET definition = 'A person who studies or learns about a particular subject.' WHERE word = 'Student' AND language = 'en';
UPDATE vocabularies SET definition = 'The part of the day from dawn to noon.' WHERE word = 'Morning' AND language = 'en';
UPDATE vocabularies SET definition = 'The period between sunset and sunrise, when a location faces far away from the sun, thus when the sky is dark.' WHERE word = 'Night' AND language = 'en';
UPDATE vocabularies SET definition = 'A happy event, thing, person, etc.' WHERE word = 'Happy' AND language = 'en';
UPDATE vocabularies SET definition = 'Someone who is beautiful. Can be used as a term of address.' WHERE word = 'Beautiful' AND language = 'en';
UPDATE vocabularies SET definition = 'Someone or something that is large in stature' WHERE word = 'Big' AND language = 'en';
UPDATE vocabularies SET definition = 'Any part of something that is smaller or slimmer than the rest, now usually with anatomical reference to the back.' WHERE word = 'Small' AND language = 'en';
UPDATE vocabularies SET definition = 'A legally or socially binding conceptual contract of entitlement to wealth, void of intrinsic value, payable for all debts and taxes, and regulated in supply.' WHERE word = 'Money' AND language = 'en';
UPDATE vocabularies SET definition = 'An animal of the family Felidae:' WHERE word = 'Cat' AND language = 'en';
UPDATE vocabularies SET definition = 'A mammal, Canis familiaris or Canis lupus familiaris, that has been domesticated for thousands of years, of highly variable appearance due to human breeding.' WHERE word = 'Dog' AND language = 'en';
UPDATE vocabularies SET definition = 'A cold-blooded vertebrate animal that lives in water, moving with the help of fins and breathing with gills.' WHERE word = 'Fish' AND language = 'en';
UPDATE vocabularies SET definition = 'A member of the class of animals Aves in the phylum Chordata, characterized by being warm-blooded, having feathers and wings usually capable of flight, and laying eggs.' WHERE word = 'Bird' AND language = 'en';
UPDATE vocabularies SET definition = 'Any of a range of colours having the longest wavelengths, 670 nm, of the visible spectrum; a primary additive colour for transmitted light: the colour obtained by subtracting green and blue from white light using magenta and yellow filters; the colour of blood, ripe strawberries, etc.' WHERE word = 'Red' AND language = 'en';
UPDATE vocabularies SET definition = 'The colour of the clear sky or the deep sea, between green and violet in the visible spectrum, and one of the primary additive colours for transmitted light; the colour obtained by subtracting red and green from white light using magenta and cyan filters; or any colour resembling this.' WHERE word = 'Blue' AND language = 'en';
UPDATE vocabularies SET definition = 'Having green as its color.' WHERE word = 'Green' AND language = 'en';
UPDATE vocabularies SET definition = 'The colour of gold, butter, or a lemon; the colour obtained by mixing green and red light, or by subtracting blue from white light.' WHERE word = 'Yellow' AND language = 'en';
UPDATE vocabularies SET definition = 'The color/colour of snow or milk; the colour of light containing equal amounts of all visible wavelengths.' WHERE word = 'White' AND language = 'en';
UPDATE vocabularies SET definition = 'The colour/color perceived in the absence of light, but also when no light is reflected, but rather absorbed.' WHERE word = 'Black' AND language = 'en';
UPDATE vocabularies SET definition = 'A (human) female who has given birth to a baby' WHERE word = 'Mother' AND language = 'en';
UPDATE vocabularies SET definition = 'A (generally human) male who begets a child.' WHERE word = 'Father' AND language = 'en';
UPDATE vocabularies SET definition = 'Son of the same parents as another person.' WHERE word = 'Brother' AND language = 'en';
UPDATE vocabularies SET definition = 'A daughter of the same parents as another person; a female sibling.' WHERE word = 'Sister' AND language = 'en';
UPDATE vocabularies SET definition = 'A physician; a member of the medical profession; one who is trained and licensed to heal the sick or injured. The final examination and qualification may award a doctor degree in which case the post-nominal letters are D.O., DPM, M.D., DMD, DDS, in the US or MBBS in the UK.' WHERE word = 'Doctor' AND language = 'en';
UPDATE vocabularies SET definition = 'A wheeled vehicle that moves independently, with at least three wheels, powered mechanically, steered by a driver and mostly for personal transportation.' WHERE word = 'Car' AND language = 'en';
UPDATE vocabularies SET definition = 'A device for transmitting conversations and other sounds in real time across distances, now often a small portable unit also capable of running software etc.' WHERE word = 'Phone' AND language = 'en';
UPDATE vocabularies SET definition = 'Furniture with a top surface to accommodate a variety of uses.' WHERE word = 'Table' AND language = 'en';
UPDATE vocabularies SET definition = 'An item of furniture used to sit on or in, comprising a seat, legs, back, and sometimes arm rests, for use by one person. Compare stool, couch, sofa, settee, loveseat and bench.' WHERE word = 'Chair' AND language = 'en';
UPDATE vocabularies SET definition = 'A portal of entry into a building, room, or vehicle, consisting of a rigid plane movable on a hinge. Doors are frequently made of wood or metal. May have a handle to help open and close, a latch to hold the door closed and a lock that ensures the door cannot be opened without the key.' WHERE word = 'Door' AND language = 'en';
UPDATE vocabularies SET definition = 'The inedible parts of a grain-producing plant.' WHERE word = 'Window' AND language = 'en';
UPDATE vocabularies SET definition = 'Something to be eaten; a meal; a food item.' WHERE word = 'Eat' AND language = 'en';
UPDATE vocabularies SET definition = 'To consume (a liquid) through the mouth.' WHERE word = 'Drink' AND language = 'en';
UPDATE vocabularies SET definition = 'To run.' WHERE word = 'Run' AND language = 'en';
UPDATE vocabularies SET definition = 'To move on the feet by alternately setting each foot (or pair or group of feet, in the case of animals with four or more feet) forward, with at least one foot on the ground at all times. Compare run.' WHERE word = 'Walk' AND language = 'en';
UPDATE vocabularies SET definition = 'To rest in a state of reduced consciousness.' WHERE word = 'Sleep' AND language = 'en';
UPDATE vocabularies SET definition = 'Condensed water falling from a cloud.' WHERE word = 'Rain' AND language = 'en';
UPDATE vocabularies SET definition = 'A star, especially when seen as the centre of any single solar system.' WHERE word = 'Sun' AND language = 'en';
UPDATE vocabularies SET definition = '(of a thing) Having a low temperature.' WHERE word = 'Cold' AND language = 'en';
UPDATE vocabularies SET definition = '(with up) To heat; to make or become hot.' WHERE word = 'Hot' AND language = 'en';
UPDATE vocabularies SET definition = 'The act of appointing a person to hold an office or to have a position of trust' WHERE word = 'Appointment' AND language = 'en';
UPDATE vocabularies SET definition = 'The effect upon the judgment or feelings produced by any event, whether witnessed or participated in; personal and direct impressions as contrasted with description or fancies; personal acquaintance; actual enjoyment or suffering.' WHERE word = 'Experience' AND language = 'en';
UPDATE vocabularies SET definition = 'A stuffed or quilted coverlet for a bed; a comforter.' WHERE word = 'Comfortable' AND language = 'en';
UPDATE vocabularies SET definition = 'Full of danger.' WHERE word = 'Dangerous' AND language = 'en';
UPDATE vocabularies SET definition = 'The body with the power to make and/or enforce laws to control a country, land area, people or organization.' WHERE word = 'Government' AND language = 'en';
UPDATE vocabularies SET definition = 'A large medical facility, usually in a building with multiple floors, where seriously ill or injured patients are given extensive medical and/or surgical treatment.' WHERE word = 'Hospital' AND language = 'en';
UPDATE vocabularies SET definition = 'A complete domicile occupying only part of a building, especially one for rent; a flat.' WHERE word = 'Apartment' AND language = 'en';
UPDATE vocabularies SET definition = 'A person living on adjacent or nearby land; a person situated adjacently or nearby; anything (of the same type of thing as the subject) in an adjacent or nearby position.' WHERE word = 'Neighbor' AND language = 'en';
UPDATE vocabularies SET definition = 'To extol or honour in a solemn manner.' WHERE word = 'Celebrate' AND language = 'en';
UPDATE vocabularies SET definition = 'To make (something) better; to increase the value or productivity (of something).' WHERE word = 'Improve' AND language = 'en';
UPDATE vocabularies SET definition = 'To make plain, manifest, or intelligible; to clear of obscurity; to illustrate the meaning of.' WHERE word = 'Explain' AND language = 'en';
UPDATE vocabularies SET definition = 'Happening quickly and with little or no warning; in a sudden manner.' WHERE word = 'Suddenly' AND language = 'en';
UPDATE vocabularies SET definition = 'An uncertainty.' WHERE word = 'Perhaps' AND language = 'en';
UPDATE vocabularies SET definition = '(usually with the definite article) A place to do the "necessary" business of urination and defecation: an outhouse or lavatory.' WHERE word = 'Necessary' AND language = 'en';
UPDATE vocabularies SET definition = 'A subjective belief, judgment or perspective that a person has formed about a topic, issue, person or thing.' WHERE word = 'Opinion' AND language = 'en';
UPDATE vocabularies SET definition = 'The act of deciding.' WHERE word = 'Decision' AND language = 'en';
UPDATE vocabularies SET definition = 'Any condition, circumstance, opportunity or means, particularly favorable to success, or to any desired end.' WHERE word = 'Advantage' AND language = 'en';
UPDATE vocabularies SET definition = 'To polish; to refine; to render polite.' WHERE word = 'Polite' AND language = 'en';
UPDATE vocabularies SET definition = 'To adorn or grace; to honour; to make becoming, appropriate, or honourable.' WHERE word = 'Honest' AND language = 'en';
UPDATE vocabularies SET definition = 'Of sinews and tendons.' WHERE word = 'Nervous' AND language = 'en';
UPDATE vocabularies SET definition = 'An airfield (an area designated for the takeoff and landing of aircraft), including one or more runways and (for commercial airports) one or more passenger terminals.' WHERE word = 'Airport' AND language = 'en';
UPDATE vocabularies SET definition = 'An official document normally used for international journeys, which proves the identity and nationality of the person for whom it was issued.' WHERE word = 'Passport' AND language = 'en';
UPDATE vocabularies SET definition = 'The bags and other containers that hold a traveller''s belongings.' WHERE word = 'Luggage' AND language = 'en';
UPDATE vocabularies SET definition = 'A pass entitling the holder to admission to a show, concert, etc.' WHERE word = 'Ticket' AND language = 'en';
UPDATE vocabularies SET definition = 'A set amount of travelling, seen as a single unit; a discrete trip, a voyage.' WHERE word = 'Journey' AND language = 'en';
UPDATE vocabularies SET definition = 'A patron, a client; one who purchases or receives a product or service from a business or merchant, or intends to do so.' WHERE word = 'Customer' AND language = 'en';
UPDATE vocabularies SET definition = 'An official face-to-face meeting of monarchs or other important figures.' WHERE word = 'Interview' AND language = 'en';
UPDATE vocabularies SET definition = 'A fixed amount of money paid to a worker, usually calculated on a monthly or annual basis, not hourly, as wages. Implies a degree of professionalism and/or autonomy.' WHERE word = 'Salary' AND language = 'en';
UPDATE vocabularies SET definition = 'A formula for preparing or using a medicine; a prescription; also, a medicine prepared from such instructions.' WHERE word = 'Recipe' AND language = 'en';
UPDATE vocabularies SET definition = 'Pleasing to taste; tasty.' WHERE word = 'Delicious' AND language = 'en';
UPDATE vocabularies SET definition = 'Enjoying health and vigor of body, mind, or spirit: well.' WHERE word = 'Healthy' AND language = 'en';
UPDATE vocabularies SET definition = 'Any activity designed to develop or hone a skill or ability.' WHERE word = 'Exercise' AND language = 'en';
UPDATE vocabularies SET definition = 'An unexpected event with negative consequences occurring without the intention of the one suffering the consequences.' WHERE word = 'Accident' AND language = 'en';
UPDATE vocabularies SET definition = 'A situation which poses an immediate risk and which requires urgent attention.' WHERE word = 'Emergency' AND language = 'en';
UPDATE vocabularies SET definition = 'To sadden or displease (someone) by underperforming, or by not delivering something promised or hoped for.' WHERE word = 'Disappointed' AND language = 'en';
UPDATE vocabularies SET definition = 'To stir the emotions of.' WHERE word = 'Excited' AND language = 'en';
UPDATE vocabularies SET definition = 'Thinking about unpleasant things that have happened or that might happen; feeling afraid and unhappy.' WHERE word = 'Worried' AND language = 'en';
UPDATE vocabularies SET definition = 'Noble in behaviour or actions; principled, not petty; kind, magnanimous.' WHERE word = 'Generous' AND language = 'en';
UPDATE vocabularies SET definition = 'A lazy person.' WHERE word = 'Lazy' AND language = 'en';
UPDATE vocabularies SET definition = 'The individual who bears the responsibility for something.' WHERE word = 'Responsible' AND language = 'en';
UPDATE vocabularies SET definition = 'That which follows something on which it depends; that which is produced by a cause.' WHERE word = 'Consequence' AND language = 'en';
UPDATE vocabularies SET definition = 'To confer with others in order to come to terms or reach an agreement.' WHERE word = 'Negotiate' AND language = 'en';
UPDATE vocabularies SET definition = 'To make stable or firm; to confirm.' WHERE word = 'Establish' AND language = 'en';
UPDATE vocabularies SET definition = 'To give something that is or becomes part of a larger whole.' WHERE word = 'Contribute' AND language = 'en';
UPDATE vocabularies SET definition = 'That which has significance; a sign; a token; a symbol.' WHERE word = 'Significant' AND language = 'en';
UPDATE vocabularies SET definition = 'The gases surrounding the Earth or any astronomical body.' WHERE word = 'Atmosphere' AND language = 'en';
UPDATE vocabularies SET definition = 'Self-assurance.' WHERE word = 'Confidence' AND language = 'en';
UPDATE vocabularies SET definition = 'To successfully convince (someone) to agree to, accept, or do something, usually through reasoning and verbal influence.' WHERE word = 'Persuade' AND language = 'en';
UPDATE vocabularies SET definition = 'The power to affect, control or manipulate something or someone; the ability to change the development of fluctuating things such as conduct, thoughts or decisions.' WHERE word = 'Influence' AND language = 'en';
UPDATE vocabularies SET definition = 'A chance for advancement, progress or profit.' WHERE word = 'Opportunity' AND language = 'en';
UPDATE vocabularies SET definition = 'The process of developing; growth, directed change.' WHERE word = 'Development' AND language = 'en';
UPDATE vocabularies SET definition = 'The people living within a political or geographical boundary.' WHERE word = 'Population' AND language = 'en';
UPDATE vocabularies SET definition = 'The surroundings of, and influences on, a particular item of interest.' WHERE word = 'Environment' AND language = 'en';
UPDATE vocabularies SET definition = 'A measure of cold or heat, often measurable with a thermometer.' WHERE word = 'Temperature' AND language = 'en';
UPDATE vocabularies SET definition = 'The act of achieving or performing; a successful performance; accomplishment' WHERE word = 'Achievement' AND language = 'en';
UPDATE vocabularies SET definition = 'To inquire into or study in order to ascertain facts or information.' WHERE word = 'Investigate' AND language = 'en';
UPDATE vocabularies SET definition = 'The act of comparing or the state or process of being compared.' WHERE word = 'Comparison' AND language = 'en';
UPDATE vocabularies SET definition = 'A part of culture that is passed from person to person or generation to generation, possibly differing in detail from family to family, such as the way to celebrate holidays.' WHERE word = 'Tradition' AND language = 'en';
UPDATE vocabularies SET definition = 'What somebody is known for.' WHERE word = 'Reputation' AND language = 'en';
UPDATE vocabularies SET definition = 'The set of courses, coursework, and their content, offered at a school or university.' WHERE word = 'Curriculum' AND language = 'en';
UPDATE vocabularies SET definition = 'The action or process of making goods systematically or on a large scale.' WHERE word = 'Manufacture' AND language = 'en';
UPDATE vocabularies SET definition = 'A commercial solicitation designed to sell some commodity, service or similar.' WHERE word = 'Advertisement' AND language = 'en';
UPDATE vocabularies SET definition = 'The action of competing.' WHERE word = 'Competition' AND language = 'en';
UPDATE vocabularies SET definition = 'One who enters into, or offers for, any service of his/her own free will, especially when done without pay.' WHERE word = 'Volunteer' AND language = 'en';
UPDATE vocabularies SET definition = 'A fellow member of a profession, staff, academic faculty or other organization; an associate.' WHERE word = 'Colleague' AND language = 'en';
UPDATE vocabularies SET definition = 'Telling the truth or giving a true result; exact; not defective or faulty' WHERE word = 'Accurate' AND language = 'en';
UPDATE vocabularies SET definition = 'A cause; something that causes an effect' WHERE word = 'Efficient' AND language = 'en';
UPDATE vocabularies SET definition = 'Possession by a god; divine inspiration or frenzy.' WHERE word = 'Enthusiasm' AND language = 'en';
UPDATE vocabularies SET definition = 'The art or science of cultivating the ground, including the harvesting of crops, and the rearing and management of livestock' WHERE word = 'Agriculture' AND language = 'en';
UPDATE vocabularies SET definition = 'The desecration of something holy or sacred; defilement, profanation.' WHERE word = 'Pollution' AND language = 'en';
UPDATE vocabularies SET definition = 'A shaking of the ground, caused by volcanic activity or movement around geologic faults.' WHERE word = 'Earthquake' AND language = 'en';
UPDATE vocabularies SET definition = 'An estimation of a future condition.' WHERE word = 'Forecast' AND language = 'en';
UPDATE vocabularies SET definition = 'To bestow commendation on; to represent favourably; to suggest, endorse or encourage as an appropriate choice.' WHERE word = 'Recommend' AND language = 'en';
UPDATE vocabularies SET definition = 'Anything that assures a certain outcome.' WHERE word = 'Guarantee' AND language = 'en';
UPDATE vocabularies SET definition = 'To understand incorrectly, while believing one has understood correctly.' WHERE word = 'Misunderstand' AND language = 'en';
UPDATE vocabularies SET definition = 'Open to multiple interpretations.' WHERE word = 'Ambiguous' AND language = 'en';
UPDATE vocabularies SET definition = 'The act of implicating.' WHERE word = 'Implications' AND language = 'en';
UPDATE vocabularies SET definition = 'Anything having substance; an essential part.' WHERE word = 'Substantial' AND language = 'en';
UPDATE vocabularies SET definition = 'Arousing controversy—a debate or discussion of opposing opinions.' WHERE word = 'Controversial' AND language = 'en';
UPDATE vocabularies SET definition = 'A thing or being, event or process, perceptible through senses; or a fact or occurrence thereof.' WHERE word = 'Phenomenon' AND language = 'en';
UPDATE vocabularies SET definition = 'A comprehensive school.' WHERE word = 'Comprehensive' AND language = 'en';
UPDATE vocabularies SET definition = 'To make worse; to make inferior in quality or value; to impair.' WHERE word = 'Deteriorate' AND language = 'en';
UPDATE vocabularies SET definition = 'Occurring at the same time.' WHERE word = 'Simultaneously' AND language = 'en';
UPDATE vocabularies SET definition = 'To admit the knowledge of; to recognize as a fact or truth; to declare one''s belief in' WHERE word = 'Acknowledge' AND language = 'en';
UPDATE vocabularies SET definition = 'To render fit, suitable, or correspondent; to adapt.' WHERE word = 'Accommodate' AND language = 'en';
UPDATE vocabularies SET definition = 'Government by bureaus or their administrators or officers.' WHERE word = 'Bureaucracy' AND language = 'en';
UPDATE vocabularies SET definition = 'Used loosely, a tentative conjecture explaining an observation, phenomenon or scientific problem that can be tested by further observation, investigation and/or experimentation. As a scientific term of art, see the attached quotation. Compare to theory, and quotation given there.' WHERE word = 'Hypothesis' AND language = 'en';
UPDATE vocabularies SET definition = '(systems theory) An underlying base or foundation especially for an organization or system.' WHERE word = 'Infrastructure' AND language = 'en';
UPDATE vocabularies SET definition = 'A subdominant.' WHERE word = 'Predominant' AND language = 'en';
UPDATE vocabularies SET definition = 'The ability to sustain something.' WHERE word = 'Sustainability' AND language = 'en';
UPDATE vocabularies SET definition = 'Never before seen, done, or experienced; without precedent.' WHERE word = 'Unprecedented' AND language = 'en';
UPDATE vocabularies SET definition = 'Susceptibility to attack or injury; the state or condition of being weak or poorly defended.' WHERE word = 'Vulnerability' AND language = 'en';
UPDATE vocabularies SET definition = 'The power, right, or authority to interpret and apply the law.' WHERE word = 'Jurisdiction' AND language = 'en';
UPDATE vocabularies SET definition = 'A person holding the stakes of bettors, with the responsibility of delivering the pot to the winner of the bet.' WHERE word = 'Stakeholder' AND language = 'en';
UPDATE vocabularies SET definition = 'To combine into a single unit; to group together or join.' WHERE word = 'Consolidate' AND language = 'en';
UPDATE vocabularies SET definition = 'A circumstance in which a choice must be made between two or more alternatives that seem equally undesirable.' WHERE word = 'Dilemma' AND language = 'en';
UPDATE vocabularies SET definition = 'Identification with or understanding of the thoughts, feelings, or emotional state of another person.' WHERE word = 'Empathy' AND language = 'en';
UPDATE vocabularies SET definition = 'The use of a word or phrase to refer to something that it is not, invoking a direct similarity between the word or phrase used and the thing described (but in the case of English without the words like or as, since use of those words would imply a simile); the word or phrase used in this way; an implied comparison.' WHERE word = 'Metaphor' AND language = 'en';
UPDATE vocabularies SET definition = 'Something that is predictable, necessary, or cannot be avoided.' WHERE word = 'Inevitable' AND language = 'en';
UPDATE vocabularies SET definition = 'To make less natural or innocent.' WHERE word = 'Sophisticated' AND language = 'en';
UPDATE vocabularies SET definition = 'The condition of being prosperous, of having good fortune' WHERE word = 'Prosperity' AND language = 'en';
UPDATE vocabularies SET definition = 'The mental ability to recover quickly from depression, illness or misfortune.' WHERE word = 'Resilience' AND language = 'en';
UPDATE vocabularies SET definition = 'Discernment, the act of discriminating, discerning, distinguishing, noting or perceiving differences between things, with intent to understand rightly and make correct decisions.' WHERE word = 'Discrimination' AND language = 'en';
UPDATE vocabularies SET definition = 'A person who organizes and operates a business venture and assumes much of the associated risk.' WHERE word = 'Entrepreneur' AND language = 'en';
UPDATE vocabularies SET definition = 'The act of innovating; the introduction of something new, in customs, rites, etc.' WHERE word = 'Innovation' AND language = 'en';
UPDATE vocabularies SET definition = 'The art and practice of conducting international relations by negotiating alliances, treaties, agreements etc., bilaterally or multilaterally, between states and sometimes international organizations, or even between polities with varying status, such as those of monarchs and their princely vassals.' WHERE word = 'Diplomacy' AND language = 'en';
UPDATE vocabularies SET definition = 'A concerted set of messages aimed at influencing the opinions or behavior of large numbers of people.' WHERE word = 'Propaganda' AND language = 'en';
UPDATE vocabularies SET definition = 'Statements made by a witness in court.' WHERE word = 'Testimony' AND language = 'en';
UPDATE vocabularies SET definition = 'A collection of ordered steps that solve a mathematical problem. A precise step-by-step plan for a computational procedure that possibly begins with an input value and yields an output value in a finite number of steps.' WHERE word = 'Algorithm' AND language = 'en';
UPDATE vocabularies SET definition = 'The process of obscuring information to make it unreadable without special knowledge, key files, or passwords.' WHERE word = 'Encryption' AND language = 'en';
UPDATE vocabularies SET definition = 'Although, despite (it) being.' WHERE word = 'Albeit' AND language = 'en';
UPDATE vocabularies SET definition = 'Simultaneously experiencing or expressing opposing or contradictory feelings, beliefs, or motivations.' WHERE word = 'Ambivalent' AND language = 'en';
UPDATE vocabularies SET definition = 'An animal of the subkingdom Articulata.' WHERE word = 'Articulate' AND language = 'en';
UPDATE vocabularies SET definition = 'Having a disposition to do good.' WHERE word = 'Benevolent' AND language = 'en';
UPDATE vocabularies SET definition = 'To avoid or get around something; to bypass' WHERE word = 'Circumvent' AND language = 'en';
UPDATE vocabularies SET definition = 'Aware; fully informed; having understanding of a fact' WHERE word = 'Cognizant' AND language = 'en';
UPDATE vocabularies SET definition = 'A statement or an idea which is unproven, but is thought to be true; a guess.' WHERE word = 'Conjecture' AND language = 'en';
UPDATE vocabularies SET definition = 'To sketch out, draw or trace an outline.' WHERE word = 'Delineate' AND language = 'en';
UPDATE vocabularies SET definition = 'To belittle or express disapproval of.' WHERE word = 'Deprecate' AND language = 'en';
UPDATE vocabularies SET definition = 'An inconsistency between facts or sentiments.' WHERE word = 'Discrepancy' AND language = 'en';
UPDATE vocabularies SET definition = 'Fluently persuasive and articulate' WHERE word = 'Eloquent' AND language = 'en';
UPDATE vocabularies SET definition = 'A word or expression capable of different meanings; an ambiguous term.' WHERE word = 'Equivocal' AND language = 'en';
UPDATE vocabularies SET definition = 'To make worse (a problem, bad situation, negative feeling, etc.); aggravate; exasperate.' WHERE word = 'Exacerbate' AND language = 'en';
UPDATE vocabularies SET definition = 'To make easy or easier.' WHERE word = 'Facilitate' AND language = 'en';
UPDATE vocabularies SET definition = 'Naturally as part or consequence of something.' WHERE word = 'Inherent' AND language = 'en';
UPDATE vocabularies SET definition = 'Characterized by very precise, conscientious attention to details.' WHERE word = 'Meticulous' AND language = 'en';
UPDATE vocabularies SET definition = 'A reduction or decrease of something harmful or unpleasant.' WHERE word = 'Mitigation' AND language = 'en';
UPDATE vocabularies SET definition = 'A minor distinction.' WHERE word = 'Nuance' AND language = 'en';
UPDATE vocabularies SET definition = 'A pattern, a way of doing something, especially a pattern of thought, a system of beliefs, a conceptual framework.' WHERE word = 'Paradigm' AND language = 'en';
UPDATE vocabularies SET definition = 'Manifested throughout; pervading, permeating, penetrating or affecting everything.' WHERE word = 'Pervasive' AND language = 'en';
UPDATE vocabularies SET definition = 'A man of business.' WHERE word = 'Pragmatic' AND language = 'en';
UPDATE vocabularies SET definition = 'To increase in number or spread rapidly; to multiply.' WHERE word = 'Proliferate' AND language = 'en';
UPDATE vocabularies SET definition = 'To restore a friendly relationship; to bring back to harmony.' WHERE word = 'Reconcile' AND language = 'en';
UPDATE vocabularies SET definition = 'To examine something with great care or detail, as to look for hidden or obscure flaws.' WHERE word = 'Scrutinize' AND language = 'en';
UPDATE vocabularies SET definition = 'A physical object, something that can be touched.' WHERE word = 'Tangible' AND language = 'en';
UPDATE vocabularies SET definition = 'Unambiguous; without equivocation or ambiguity; singularly clear, unmistakable, or unquestionable' WHERE word = 'Unequivocal' AND language = 'en';
UPDATE vocabularies SET definition = 'To clear of an accusation, suspicion or criticism.' WHERE word = 'Vindicate' AND language = 'en';
UPDATE vocabularies SET definition = 'To confirm or support something with additional evidence; to attest or vouch for.' WHERE word = 'Corroborate' AND language = 'en';
UPDATE vocabularies SET definition = 'To vary irregularly; to swing.' WHERE word = 'Fluctuate' AND language = 'en';
UPDATE vocabularies SET definition = 'A body of authoritative officials organized in nested ranks.' WHERE word = 'Hierarchy' AND language = 'en';
UPDATE vocabularies SET definition = 'A chronological mistake; the erroneous dating of an event, circumstance, or object.' WHERE word = 'Anachronism' AND language = 'en';
UPDATE vocabularies SET definition = 'The fact or action of becoming or making into a god; deification.' WHERE word = 'Apotheosis' AND language = 'en';
UPDATE vocabularies SET definition = 'Impulsive and unpredictable; determined by chance, impulse, or whim' WHERE word = 'Capricious' AND language = 'en';
UPDATE vocabularies SET definition = 'Deception by use of trickery, quibbling, or subterfuge.' WHERE word = 'Chicanery' AND language = 'en';
UPDATE vocabularies SET definition = 'To reduce to a common measure.' WHERE word = 'Commensurate' AND language = 'en';
UPDATE vocabularies SET definition = 'To come down from one''s superior position; to deign (to do something).' WHERE word = 'Condescending' AND language = 'en';
UPDATE vocabularies SET definition = 'An abusive, bitter, attack or criticism: denunciation.' WHERE word = 'Diatribe' AND language = 'en';
UPDATE vocabularies SET definition = 'Enthusiastic; high-spirited.' WHERE word = 'Ebullient' AND language = 'en';
UPDATE vocabularies SET definition = 'Something which lasts for a short period of time.' WHERE word = 'Ephemeral' AND language = 'en';
UPDATE vocabularies SET definition = 'The state of being calm, stable and composed, especially under stress.' WHERE word = 'Equanimity' AND language = 'en';
UPDATE vocabularies SET definition = 'An esoteric doctrine or treatise; esoteric philosophy.' WHERE word = 'Esoteric' AND language = 'en';
UPDATE vocabularies SET definition = 'Without preparation or advanced thought; offhand.' WHERE word = 'Extemporaneous' AND language = 'en';
UPDATE vocabularies SET definition = 'Excessively or tiresomely talkative.' WHERE word = 'Garrulous' AND language = 'en';
UPDATE vocabularies SET definition = 'Domination, influence, or authority over another, especially by one political group over a society or by one nation over others.' WHERE word = 'Hegemony' AND language = 'en';
UPDATE vocabularies SET definition = 'Peculiar to a specific individual; eccentric.' WHERE word = 'Idiosyncratic' AND language = 'en';
UPDATE vocabularies SET definition = 'Lacking money' WHERE word = 'Impecunious' AND language = 'en';
UPDATE vocabularies SET definition = 'Talkative; chatty.' WHERE word = 'Loquacious' AND language = 'en';
UPDATE vocabularies SET definition = 'Noble and generous in spirit.' WHERE word = 'Magnanimous' AND language = 'en';
UPDATE vocabularies SET definition = '(of a person) Lying, untruthful or dishonest.' WHERE word = 'Mendacious' AND language = 'en';
UPDATE vocabularies SET definition = 'To make dark; overshadow' WHERE word = 'Obfuscate' AND language = 'en';
UPDATE vocabularies SET definition = 'Of acute discernment; having keen insight; mentally perceptive.' WHERE word = 'Perspicacious' AND language = 'en';
UPDATE vocabularies SET definition = 'Causing much harm in a subtle way.' WHERE word = 'Pernicious' AND language = 'en';
UPDATE vocabularies SET definition = 'A recondite (hidden or obscure) person or thing.' WHERE word = 'Recondite' AND language = 'en';
UPDATE vocabularies SET definition = 'One who uses obsequious compliments to gain self-serving favor or advantage from another; a servile flatterer.' WHERE word = 'Sycophant' AND language = 'en';
UPDATE vocabularies SET definition = 'Having a tendency; written or spoken with a partisan, biased or prejudiced purpose, especially a controversial one.' WHERE word = 'Tendentious' AND language = 'en';
