INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Apple', 'Quả táo', 'A round fruit with red or green skin and a whitish interior.', 'en', 'A1', 1, '/ˈæp.əl/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Banana', 'Quả chuối', 'A long curved fruit which grows in clusters and has yellow skin.', 'en', 'A1', 1, '/bəˈnæn.ə/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Milk', 'Sữa', 'An opaque white fluid rich in fat and protein.', 'en', 'A1', 1, '/mɪlk/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Bread', 'Bánh mì', 'Food made of flour, water, and yeast mixed together and baked.', 'en', 'A1', 1, '/brɛd/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Egg', 'Quả trứng', 'An oval or round object laid by a female bird.', 'en', 'A1', 1, '/ɛɡ/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Meat', 'Thịt', 'The flesh of an animal as food.', 'en', 'A1', 1, '/miːt/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Chicken', 'Con gà', 'A domestic fowl kept for its eggs or meat.', 'en', 'A1', 1, '/ˈtʃɪk.ɪn/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Run', 'Chạy', 'Move at a speed faster than a walk.', 'en', 'A1', 1, '/rʌn/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Jump', 'Nhảy', 'Push oneself off a surface and into the air.', 'en', 'A1', 1, '/dʒʌmp/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Sit', 'Ngồi', 'Adopt or be in a position in which one''s weight is supported by one''s buttocks.', 'en', 'A1', 1, '/sɪt/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Stand', 'Đứng', 'Have or maintain an upright position.', 'en', 'A1', 1, '/stænd/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Drink', 'Uống', 'Take a liquid into the mouth and swallow.', 'en', 'A1', 1, '/drɪŋk/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Play', 'Chơi', 'Engage in activity for enjoyment and recreation.', 'en', 'A1', 1, '/pleɪ/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Read', 'Đọc', 'Look at and comprehend the meaning of written or printed matter.', 'en', 'A1', 1, '/riːd/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Write', 'Viết', 'Mark on a surface with a pen, pencil, or similar implement.', 'en', 'A1', 1, '/raɪt/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Speak', 'Nói', 'Say something in order to convey information.', 'en', 'A1', 1, '/spiːk/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Listen', 'Nghe', 'Give one''s attention to a sound.', 'en', 'A1', 1, '/ˈlɪs.ən/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('See', 'Nhìn', 'Perceive with the eyes.', 'en', 'A1', 1, '/siː/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Hear', 'Nghe thấy', 'Perceive with the ear the sound made by someone or something.', 'en', 'A1', 1, '/hɪər/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Today', 'Hôm nay', 'On or in the course of this present day.', 'en', 'A1', 1, '/təˈdeɪ/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Tomorrow', 'Ngày mai', 'On the day after today.', 'en', 'A1', 1, '/təˈmɒr.oʊ/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Yesterday', 'Hôm qua', 'On the day before today.', 'en', 'A1', 1, '/ˈjɛs.tər.deɪ/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Week', 'Tuần', 'A period of seven days.', 'en', 'A1', 1, '/wiːk/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Month', 'Tháng', 'Each of the twelve named periods into which a year is divided.', 'en', 'A1', 1, '/mʌnθ/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Year', 'Năm', 'The time taken by the earth to make one revolution around the sun.', 'en', 'A1', 1, '/jɪər/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Fascinating', 'Hấp dẫn', 'Extremely interesting.', 'en', 'B2', 3, '/ˈfæs.ɪ.neɪ.tɪŋ/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Inevitably', 'Chắc chắn xảy ra', 'As is certain to happen; unavoidably.', 'en', 'B2', 3, '/ɪˈnɛv.ɪ.tə.bli/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Convey', 'Truyền đạt', 'Transport or carry to a place.', 'en', 'B2', 3, '/kənˈveɪ/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Crucial', 'Quan trọng', 'Decisive or critical, especially in the success or failure of something.', 'en', 'B2', 3, '/ˈkruː.ʃəl/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Vast', 'Rộng lớn', 'Of very great extent or quantity; immense.', 'en', 'B2', 3, '/vɑːst/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Subtle', 'Tinh tế', 'So delicate or precise as to be difficult to analyze or describe.', 'en', 'B2', 3, '/ˈsʌt.əl/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Profound', 'Sâu sắc', 'Very great or intense.', 'en', 'B2', 3, '/prəˈfaʊnd/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Abundant', 'Dồi dào', 'Existing or available in large quantities; plentiful.', 'en', 'B2', 3, '/əˈbʌn.dənt/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Emerge', 'Xuất hiện', 'Move out of or away from something and come into view.', 'en', 'B2', 3, '/ɪˈmɜːdʒ/');
INSERT INTO vocabularies (word, meaning, definition, language, level, difficulty, ipa) VALUES ('Pivotal', 'Then chốt', 'Of crucial importance in relation to the development or success of something else.', 'en', 'B2', 3, '/ˈpɪv.ə.təl/');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('今天', 'Hôm nay', 'zh', 'HSK1', 1, 'jīn tiān');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('明天', 'Ngày mai', 'zh', 'HSK1', 1, 'míng tiān');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('昨天', 'Hôm qua', 'zh', 'HSK1', 1, 'zuó tiān');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('喜欢', 'Thích', 'zh', 'HSK1', 1, 'xǐ huān');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('电视', 'Tivi', 'zh', 'HSK1', 1, 'diàn shì');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('电影', 'Phim', 'zh', 'HSK1', 1, 'diàn yǐng');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('看', 'Nhìn, xem', 'zh', 'HSK1', 1, 'kàn');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('听', 'Nghe', 'zh', 'HSK1', 1, 'tīng');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('说', 'Nói', 'zh', 'HSK1', 1, 'shuō');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('读', 'Đọc', 'zh', 'HSK1', 1, 'dú');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('写', 'Viết', 'zh', 'HSK1', 1, 'xiě');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('不', 'Không', 'zh', 'HSK1', 1, 'bù');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('很', 'Rất', 'zh', 'HSK1', 1, 'hěn');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('和', 'Và', 'zh', 'HSK1', 1, 'hé');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('在', 'Ở', 'zh', 'HSK1', 1, 'zài');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('有', 'Có', 'zh', 'HSK1', 1, 'yǒu');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('没有', 'Không có', 'zh', 'HSK1', 1, 'méi yǒu');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('是', 'Là', 'zh', 'HSK1', 1, 'shì');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('去', 'Đi', 'zh', 'HSK1', 1, 'qù');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('来', 'Đến', 'zh', 'HSK1', 1, 'lái');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('突然', 'Đột nhiên', 'zh', 'HSK3', 2, 'tū rán');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('马上', 'Ngay lập tức', 'zh', 'HSK3', 2, 'mǎ shàng');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('要求', 'Yêu cầu', 'zh', 'HSK3', 2, 'yāo qiú');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('注意', 'Chú ý', 'zh', 'HSK3', 2, 'zhù yì');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('决定', 'Quyết định', 'zh', 'HSK3', 2, 'jué dìng');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('解决', 'Giải quyết', 'zh', 'HSK3', 2, 'jiě jué');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('经过', 'Trải qua, đi qua', 'zh', 'HSK3', 2, 'jīng guò');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('除了', 'Ngoài ra', 'zh', 'HSK3', 2, 'chú le');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('必须', 'Bắt buộc', 'zh', 'HSK3', 2, 'bì xū');
INSERT INTO vocabularies (word, meaning, language, level, difficulty, pinyin) VALUES ('比较', 'Khá là', 'zh', 'HSK3', 2, 'bǐ jiào');
