name: Deploy Next.js & Go to GKE

on:
  workflow_run:
    workflows: ["CI/CD Quality Gate"]
    branches: [main]
    types: [completed]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  PROJECT_ID: lingo-sniper-prod
  GAR_LOCATION: asia-southeast1
  REGION: asia-southeast1-a
  REPOSITORY: lingo-sniper
  CLUSTER_NAME: lingo-sniper-cluster
  GITHUB_REPO: tinhuynh1/language-arena
  
  # === YOU NEED TO REPLACE (UPDATE) THIS VARIABLE AFTER RUNNING WIF SCRIPT ===
  # Format: projects/123456789/locations/global/workloadIdentityPools/github-pool/providers/github-provider
  WORKLOAD_IDENTITY_PROVIDER: 'projects/696260201579/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
  
  # === YOU NEED TO REPLACE (UPDATE) THIS VARIABLE AS A GITHUB SECRET ===
  # But temporarily we hardcode the email here for demo purposes
  SERVICE_ACCOUNT: 'github-actions@lingo-sniper-prod.iam.gserviceaccount.com'

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: 'read'
      id-token: 'write' # Mandatory for WIF

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        token_format: 'access_token'
        workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ env.SERVICE_ACCOUNT }}'

    - name: Authenticate Docker to GAR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.CLUSTER_NAME }}
        location: ${{ env.REGION }}

    - name: Build and Push Backend
      run: |
        docker buildx build --platform linux/amd64 -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/backend:${{ github.sha }} ./backend
        docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/backend:${{ github.sha }}

    - name: Build and Push Frontend
      run: |
        docker buildx build --platform linux/amd64 -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/frontend:${{ github.sha }} ./frontend
        docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/frontend:${{ github.sha }}

    - name: Set up Kustomize
      run: |
        curl -sLo kustomize.tar.gz "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.6.0/kustomize_v5.6.0_linux_amd64.tar.gz"
        tar xzf kustomize.tar.gz
        sudo mv kustomize /usr/local/bin/

    - name: Deploy to GKE
      run: |
        cd k8s
        # Replace image tag with Github Commit SHA
        kustomize edit set image asia-southeast1-docker.pkg.dev/lingo-sniper-prod/lingo-sniper/backend=asia-southeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/backend:${{ github.sha }}
        kustomize edit set image asia-southeast1-docker.pkg.dev/lingo-sniper-prod/lingo-sniper/frontend=asia-southeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/frontend:${{ github.sha }}
        
        # Apply config instead of raw manifest
        kustomize build . | kubectl apply -f -
        
        # Wait for Pods to stabilize
        kubectl rollout status deployment/backend -n lingo-sniper --timeout=300s
        kubectl rollout status deployment/frontend -n lingo-sniper --timeout=300s
